### ISSUE TITLE
[APP SUBMITTED]: global name 'MULTI_EP_RESULT' is not defined

### ISSUE THREAD

**Issue by noze2000** [SiCKRAGETV/sickrage-issues#1201]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-95451 :: [IPTorrents] :: Error while searching IPTorrents, skipping: global name 'MULTI_EP_RESULT' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@gborri

**Comment by gborri** [comment]
@fernandog sorry I have no account on iptorrent. to fix it i think you have to add from sickbeard.common import MULTI_EP_RESULT, SEASON_RESULT, USER_AGENT
 on iptorrent.py

**Comment by fernandog** [comment]
@abeloin did we merged the multi ep result? Shouldn't all provider be updated too together with the PR?

**Comment by abeloin** [comment]
PR will be merged shortly in develop and be available in master on next Sunday

**Comment by fernandog** [comment]
@noze2000 please update and report back

**Comment by noze2000** [comment]
Done.
This issue seems to have disappeared when searing IPTorrent.
Thank you.

**Comment by noze2000** [comment]
2015-04-14 08:13:11 SEARCHQUEUE-BACKLOG-95451 :: [IPTorrents] :: Error while searching IPTorrents, skipping: global name 'MULTI_EP_RESULT' is not defined

Unfortunately, the issue remains.

**Comment by fernandog** [comment]
@noze2000 wasnt merged. PR is still open

**Comment by abeloin** [comment]
PR is now merged

**Comment by noze2000** [comment]
2015-04-15 06:56:13 Thread-44 :: "/Apps/bin/git" fetch origin returned
: error: Ref refs/remotes/origin/develop is at
b766ad3a36242b5a34345f63237cc8427db92236 but expected
b8bb0939a3eb11d7d3aae567bef76259549631d0
From https://github.com/SiCKRAGETV/SickRage
 ! b8bb093..b766ad3  develop    -> origin/develop  (unable to update local ref)

**Comment by noze2000** [comment]
2015-04-15 18:22:06 SEARCHQUEUE-BACKLOG-95451 :: [IPTorrents] :: Error
while searching IPTorrents, skipping: global name 'MULTI_EP_RESULT' is
not defined
2015-04-15 18:20:15 SEARCHQUEUE-BACKLOG-263365 :: [IPTorrents] ::
Error while searching IPTorrents, skipping: global name
'MULTI_EP_RESULT' is not defined

**Comment by fernandog** [comment]
@noze2000 are you in develop? If not wait until sunday to be merged in master

**Comment by noze2000** [comment]
ah..that was why.
Ill wait

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1309

IPT working again

**Comment by charles63** [comment]
Having same issue on IPT now
