### ISSUE TITLE
Local Timezone

### ISSUE THREAD

**Issue by mckinnon81** [SiCKRAGETV/sickrage-issues#2033]
I seem to be having issues with Sickrage and Timezones. Sickrage is set to Local Timezone. Timezone on system is set to GMT+10 (Australia/Brisbane) But sickrage is still showing all times and show information as Network Times. Have tried Mass updated have even removed a show and added it again but to no avail. Any ideas?

**Comment by neoatomic** [comment]
Go to General --> interface. 
There are the time settings. And check the setting " Timezone:"

**Comment by mckinnon81** [comment]
Sickrage is set to Local Timezone. but times are all network still.

**Comment by neoatomic** [comment]
There were some issues with the time zone, but those where specific to Windows and should be fixed. https://github.com/SiCKRAGETV/sickrage-issues/issues/2012
Check if there are any updates you have missed. 

We will need some more info than, can you follow this guideline and post as much info as you can.?
https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by mckinnon81** [comment]
I am running Debian Linux Jessie.

[root@sylvester /home/moe/.sickrage (git::master)]$ cat /etc/timezone
Australia/Brisbane

[root@sylvester /home/moe/.sickrage (git::master)]$ git branch -vvv
* master 287a0eb [origin/master] Merge branch 'hotfix-2041'

**Comment by miigotu** [comment]
@mckinnon81 Try to force a refresh or full update on a show, and see if it gets fixed for that show.

**Comment by mckinnon81** [comment]
I have done a force full update but still all showing network times.

This is a fresh install as well and I have only one show added currently. But before when I had all show added was still having the same issues.

2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: No new cache images needed, not retrieving new ones
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Checking if file /home/moe/.sickrage/cache/images/281714.fanart.jpg exists
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Checking if file /home/moe/.sickrage/cache/images/thumbnails/281714.banner.jpg exists
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Checking if file /home/moe/.sickrage/cache/images/thumbnails/281714.poster.jpg exists
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Checking if file /home/moe/.sickrage/cache/images/281714.banner.jpg exists
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Checking if file /home/moe/.sickrage/cache/images/281714.poster.jpg exists
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Checking if we need any cache images for show 281714
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Checking & filling cache for show Ballers
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: 281714: Retrieving/creating episode 1x3
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: 281714: Retrieving/creating episode 1x2
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: 281714: Retrieving/creating episode 1x1
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: 281714: Writing NFOs for all episodes
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: 281714: Writing NFOs for show
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Running metadata routines for Sony PS3
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Running metadata routines for WDTV
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Running metadata routines for Mede8er
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Running metadata routines for TIVO
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Running metadata routines for KODI
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Running metadata routines for MediaBrowser
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Running metadata routines for KODI 12+
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: 281714: Loading all episodes with a location from the database
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Transaction with 3 queries executed
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Using cached parse result for: Ballers - S01E03 - Move the Chains
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Transaction with 1 queries executed
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Setter sets location to /data/tvshows/Ballers/Season 1/Ballers - S01E03 - Move the Chains.mp4
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: 281714: /data/tvshows/Ballers/Season 1/Ballers - S01E03 - Move the Chains.mp4 parsed to Ballers 1x3
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Using cached parse result for: /data/tvshows/Ballers/Season 1/Ballers - S01E03 - Move the Chains.mp4
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: 281714: Creating episode object from /data/tvshows/Ballers/Season 1/Ballers - S01E03 - Move the Chains.mp4
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: 281714: Creating episode from /data/tvshows/Ballers/Season 1/Ballers - S01E03 - Move the Chains.mp4
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Using cached parse result for: Ballers - S01E02 - Raise Up
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Transaction with 1 queries executed
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Setter sets location to /data/tvshows/Ballers/Season 1/Ballers - S01E02 - Raise Up.mp4
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: 281714: /data/tvshows/Ballers/Season 1/Ballers - S01E02 - Raise Up.mp4 parsed to Ballers 1x2
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Using cached parse result for: /data/tvshows/Ballers/Season 1/Ballers - S01E02 - Raise Up.mp4
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: 281714: Creating episode object from /data/tvshows/Ballers/Season 1/Ballers - S01E02 - Raise Up.mp4
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: 281714: Creating episode from /data/tvshows/Ballers/Season 1/Ballers - S01E02 - Raise Up.mp4
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Using cached parse result for: Ballers - S01E01 - Pilot
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Transaction with 1 queries executed
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Setter sets location to /data/tvshows/Ballers/Season 1/Ballers - S01E01 - Pilot.mp4
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: 281714: /data/tvshows/Ballers/Season 1/Ballers - S01E01 - Pilot.mp4 parsed to Ballers 1x1
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: Using cached parse result for: /data/tvshows/Ballers/Season 1/Ballers - S01E01 - Pilot.mp4
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: 281714: Creating episode object from /data/tvshows/Ballers/Season 1/Ballers - S01E01 - Pilot.mp4
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: 281714: Creating episode from /data/tvshows/Ballers/Season 1/Ballers - S01E01 - Pilot.mp4
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: 281714: Found files: [u'/data/tvshows/Ballers/Season 1/Ballers - S01E01 - Pilot.mp4', u'/data/tvshows/Ballers/Season 1/Ballers - S01E02 - Raise Up.mp4', u'/data/tvshows/Ballers/Season 1/Ballers - S01E03 - Move the Chains.mp4']
2015-07-11 11:51:33 DEBUG    SHOWQUEUE-REFRESH :: 281714: Loading all episodes from the show directory /data/tvshows/Ballers
2015-07-11 11:51:33 INFO     SHOWQUEUE-REFRESH :: Performing refresh on Ballers
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Removing 1x9 from the DB list
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Removing 1x8 from the DB list
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Removing 1x7 from the DB list
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Removing 1x6 from the DB list
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Removing 1x5 from the DB list
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Removing 1x4 from the DB list
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Removing 1x3 from the DB list
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Removing 1x2 from the DB list
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Removing 1x1 from the DB list
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Saving show info to database
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Transaction with 9 queries executed
2015-07-11 11:51:31 INFO     SHOWQUEUE-FORCE-UPDATE :: The episode was deleted, skipping the rest of the load
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Deleting myself from the database
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Removing myself from my show's list
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Deleting Ballers 1x10 from the DB
2015-07-11 11:51:31 INFO     SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x10) has no name on theTVDB
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x10
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Episode 1x10 not found in the database
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from DB for episode 1x10
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: An object for episode 1x10 didn't exist in the cache, trying to create it
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Episode airs in the future, marking it 1
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x9) has no absolute number on theTVDB
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x9
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading info from theTVDB for episode 1x9
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Episode airs in the future, marking it 1
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x9) has no absolute number on theTVDB
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x9
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Episode airs in the future, marking it 1
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x8) has no absolute number on theTVDB
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x8
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading info from theTVDB for episode 1x8
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Episode airs in the future, marking it 1
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x8) has no absolute number on theTVDB
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x8
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Episode airs in the future, marking it 1
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x7) has no absolute number on theTVDB
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x7
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading info from theTVDB for episode 1x7
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Episode airs in the future, marking it 1
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x7) has no absolute number on theTVDB
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x7
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Episode airs in the future, marking it 1
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x6) has no absolute number on theTVDB
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x6
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading info from theTVDB for episode 1x6
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Episode airs in the future, marking it 1
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x6) has no absolute number on theTVDB
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x6
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Episode airs in the future, marking it 1
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x5) has no absolute number on theTVDB
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x5
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading info from theTVDB for episode 1x5
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Episode airs in the future, marking it 1
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x5) has no absolute number on theTVDB
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x5
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Episode airs in the future, marking it 1
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x4) has no absolute number on theTVDB
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x4
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading info from theTVDB for episode 1x4
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Episode airs in the future, marking it 1
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x4) has no absolute number on theTVDB
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x4
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Setting status for 1x3 based on status 104 and existence of /data/tvshows/Ballers/Season 1/Ballers - S01E03 - Move the Chains.mp4
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x3) has no absolute number on theTVDB
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x3
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading info from theTVDB for episode 1x3
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Setting status for 1x3 based on status 104 and existence of /data/tvshows/Ballers/Season 1/Ballers - S01E03 - Move the Chains.mp4
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x3) has no absolute number on theTVDB
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x3
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Setting status for 1x2 based on status 104 and existence of /data/tvshows/Ballers/Season 1/Ballers - S01E02 - Raise Up.mp4
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x2) has no absolute number on theTVDB
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x2
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading info from theTVDB for episode 1x2
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Setting status for 1x2 based on status 104 and existence of /data/tvshows/Ballers/Season 1/Ballers - S01E02 - Raise Up.mp4
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x2) has no absolute number on theTVDB
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x2
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Setting status for 1x1 based on status 104 and existence of /data/tvshows/Ballers/Season 1/Ballers - S01E01 - Pilot.mp4
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: The absolute_number for 1x1 is : 1
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x1
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading info from theTVDB for episode 1x1
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Setting status for 1x1 based on status 104 and existence of /data/tvshows/Ballers/Season 1/Ballers - S01E01 - Pilot.mp4
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: The absolute_number for 1x1 is : 1
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x1
2015-07-11 11:51:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading all episodes from theTVDB..
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Loading all episodes from theTVDB
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Episode airs in the future, marking it 1
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x9) has no absolute number on theTVDB
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x9
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from DB for episode 1x9
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from DB for episode 1x9
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: An object for episode 1x9 didn't exist in the cache, trying to create it
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Loading episode 1x9 from the DB
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Episode airs in the future, marking it 1
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x8) has no absolute number on theTVDB
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x8
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from DB for episode 1x8
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from DB for episode 1x8
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: An object for episode 1x8 didn't exist in the cache, trying to create it
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Loading episode 1x8 from the DB
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Episode airs in the future, marking it 1
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x7) has no absolute number on theTVDB
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x7
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from DB for episode 1x7
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from DB for episode 1x7
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: An object for episode 1x7 didn't exist in the cache, trying to create it
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Loading episode 1x7 from the DB
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Episode airs in the future, marking it 1
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x6) has no absolute number on theTVDB
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x6
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from DB for episode 1x6
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from DB for episode 1x6
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: An object for episode 1x6 didn't exist in the cache, trying to create it
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Loading episode 1x6 from the DB
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Episode airs in the future, marking it 1
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x5) has no absolute number on theTVDB
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x5
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from DB for episode 1x5
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from DB for episode 1x5
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: An object for episode 1x5 didn't exist in the cache, trying to create it
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Loading episode 1x5 from the DB
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Episode airs in the future, marking it 1
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x4) has no absolute number on theTVDB
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x4
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from DB for episode 1x4
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from DB for episode 1x4
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: An object for episode 1x4 didn't exist in the cache, trying to create it
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Loading episode 1x4 from the DB
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Setting status for 1x3 based on status 104 and existence of /data/tvshows/Ballers/Season 1/Ballers - S01E03 - Move the Chains.mp4
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x3) has no absolute number on theTVDB
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x3
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Setter sets location to /data/tvshows/Ballers/Season 1/Ballers - S01E03 - Move the Chains.mp4
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from DB for episode 1x3
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Setter sets location to /data/tvshows/Ballers/Season 1/Ballers - S01E03 - Move the Chains.mp4
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from DB for episode 1x3
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: An object for episode 1x3 didn't exist in the cache, trying to create it
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Loading episode 1x3 from the DB
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Setting status for 1x2 based on status 104 and existence of /data/tvshows/Ballers/Season 1/Ballers - S01E02 - Raise Up.mp4
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: This episode (Ballers - 1x2) has no absolute number on theTVDB
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x2
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Setter sets location to /data/tvshows/Ballers/Season 1/Ballers - S01E02 - Raise Up.mp4
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from DB for episode 1x2
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Setter sets location to /data/tvshows/Ballers/Season 1/Ballers - S01E02 - Raise Up.mp4
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from DB for episode 1x2
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: An object for episode 1x2 didn't exist in the cache, trying to create it
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Loading episode 1x2 from the DB
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Setting status for 1x1 based on status 104 and existence of /data/tvshows/Ballers/Season 1/Ballers - S01E01 - Pilot.mp4
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: The absolute_number for 1x1 is : 1
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from theTVDB for episode 1x1
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Setter sets location to /data/tvshows/Ballers/Season 1/Ballers - S01E01 - Pilot.mp4
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from DB for episode 1x1
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Setter sets location to /data/tvshows/Ballers/Season 1/Ballers - S01E01 - Pilot.mp4
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading episode details from DB for episode 1x1
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: An object for episode 1x1 didn't exist in the cache, trying to create it
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Loading episode 1x1 from the DB
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Loading all episodes from the DB
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Loading all episodes from the database
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Saving show info to database
2015-07-11 11:51:30 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Obtained info from IMDb ->{'rating': 7.6, 'votes': 2984, 'countries': u'USA', 'title': u'Ballers', 'genres': u'Comedy|Drama|Sport', 'imdb_id': u'tt2891574', 'country_codes': u'us', 'year': 2015, 'certificates': u'TV-MA', 'runtimes': u'30', 'akas': u'Ballers::Poland (imdb display title)|Gracze::Poland (imdb display title)|Nagyp\xe1ly\xe1sok::Hungary (imdb display title)', 'last_update': 735790}
2015-07-11 11:51:25 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading show info from IMDb
2015-07-11 11:51:25 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Retrieving show info from IMDb
2015-07-11 11:51:24 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2015-07-11 11:51:24 WARNING  SEARCHQUEUE-DAILY-SEARCH :: No NZB/Torrent providers found or enabled in the sickrage config for daily searches. Please check your settings.
2015-07-11 11:51:24 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from Ballers
2015-07-11 11:51:24 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2015-07-11 11:51:24 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 281714: Loading show info from theTVDB
2015-07-11 11:51:24 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Retrieving show info from theTVDB
2015-07-11 11:51:24 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Beginning update of Ballers
2015-07-11 11:51:22 INFO     DAILYSEARCHER :: No new released episodes found ...
2015-07-11 11:51:22 INFO     DAILYSEARCHER :: Searching for new released episodes ...

**Comment by miigotu** [comment]
Check your tvshow.nfo and see if the time is right there.

**Comment by mckinnon81** [comment]
here is the tvshow.nfo for a show.

<tvshow>
  <title>Ballers</title>
  <rating />
  <year>2015</year>
  <plot>A series centered around a group of football players and their families, friends, and handlers.</plot>
  <episodeguide>
    <url>http://thetvdb.com/api/F9C450E78D99172E/series/281714/all/en.zip</url>
  </episodeguide>
  <mpaa />
  <id>281714</id>
  <genre>Comedy / Drama / Sport</genre>
  <premiered>2015-06-21</premiered>
  <studio>HBO</studio>
  <actor>
    <name />
    <role />
    <thumb />
  </actor>
  <actor>
    <name />
    <role />
    <thumb />
  </actor>
  <id>281714</id>
  <id>281714</id>
  <id>281714</id>
  <id>281714</id>
</tvshow>

But here is the strange thing. When I add a show (no existing) then reprocess the files the same thing is still happening. Even with those that so not exist that I add the shows are still network time.

**Comment by mckinnon81** [comment]
I rolled back to an old fork i had on github - branch 207bd7a and now all the local times are correct.

**Comment by mckinnon81** [comment]
No pulling direct from sickrage github didn't work. Only way to keep local timezone was to use my form. Set General --> Local add a show and confirm local time zone is correct then update to newer sickrage version.

**Comment by miigotu** [comment]
Since noone else seems to have this issue, and it's only about displaying times, this is way back burner right now.

**Comment by fernandog** [comment]
@mckinnon81 
mine is working. Don't need to restart to mass update. I only change the option in UI and re-open "Coming Episodes" page

Network:
![network](https://cloud.githubusercontent.com/assets/2620870/8649138/966ed8a2-293d-11e5-8758-848e4d77b61e.png)

Local:
![local](https://cloud.githubusercontent.com/assets/2620870/8649146/9c8c9d64-293d-11e5-843f-a473ee684a94.png)

**Comment by SATAN999** [comment]
I have tried everything to get shows to display on local time. nothing seems to work!
In the past few weeks I've had with passing torrents to transmission (now fixed)
All shows suddenly being skipped, instead of downloaded and shows not showing in local time!
I love Sickrage, been using it for ages with no problems, but lately it's such a PITA!

**Comment by miigotu** [comment]
@SATAN999 Many changes recently, bugs happen.

`All shows suddenly being skipped, instead of downloaded`
Edit your shows and set the default status to wanted instead of skipped.
Set the ones that were marked skipped before that to wanted.

Local time we cannot reproduce the issue yet, but once we do we will fix it.

**Comment by fernandog** [comment]
@SATAN999 did you see my post?

**Comment by SATAN999** [comment]
@fernandog Which post?

**Comment by fernandog** [comment]
@SATAN999 
https://github.com/SiCKRAGETV/sickrage-issues/issues/2033#issuecomment-120903003
