### ISSUE TITLE
Sutbtitle download

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#2067]
Ive just noticed something ,that the subtitles werent showing up on Plex ,so i went to the history page and saw that they aere being showed there as downloaded ,so i went to the show`s folder and saw that the srt file had the original download name and not the "renamed" one from PP 
This happens on the lattest commit
@miigotu

**Comment by abibouba** [comment]
I confirm that there is a big mess with subtitles since the last update.
1) They are not renamed to the correct filename
2) Multiple versions for the same episode are downloaded
3) In "Missing subtitles", all the episodes of all the tv shows show up
4) As a consequence, hundred of subs are being dowloaded

**Comment by fernandog** [comment]
@abibouba do you have subtitles enabled for all tv-shows?

**Comment by abibouba** [comment]
@fernandog yes.

**Comment by fernandog** [comment]
no subtitles was available before ? if don't, SR is downloading because you don't have any subs and set it to download sub for all your tv-shows

**Comment by abibouba** [comment]
Subtitles were already downloaded for all the shows.

**Comment by fernandog** [comment]
@matigonkas please post screenshots, logs or something that would help debug it.

**Comment by abibouba** [comment]
![capture d ecran 2015-07-11 a 18 44 04](https://cloud.githubusercontent.com/assets/672894/8634534/f15faa12-27fc-11e5-92f4-71b91b141d78.png)

The first two subtitles of the list were renamed manually by me (as renaming didn't work). The other four were downloaded after by sickrage.

**Comment by abibouba** [comment]
Show "Arrow" has 69 episodes. For all of them subs are already downloaded:

![capture d ecran 2015-07-11 a 18 46 42](https://cloud.githubusercontent.com/assets/672894/8634544/555ba07a-27fd-11e5-9318-93f60b0e458f.png)

It shows up anyway in "missing subtitles":
![capture d ecran 2015-07-11 a 18 47 31](https://cloud.githubusercontent.com/assets/672894/8634549/7f114e60-27fd-11e5-86f2-8de99d6fadd4.png)

**Comment by miigotu** [comment]
@abibouba there were some issue with subtitle renaming and unlinking when I first merged, but I fixed them within the first 24 hours. Just remove the ones that are not supposed to be there, and do a rescan on the show.

**Comment by matigonkas** [comment]
My case is just like the one of abibouba But with a diferentes show and some even happened in the past hours

**Comment by miigotu** [comment]
I see a bug here, lemme figure it out.

**Comment by miigotu** [comment]
```
miigotu@PC:~/Projects/SickRage $ ls Shows/Game\ of\ Thrones/Season\ 05/*
Shows/Game of Thrones/Season 05/Game of Thrones - S05E02 - The House of Black and White.de.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E02 - The House of Black and White.es.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E02 - The House of Black and White.fr.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E02 - The House of Black and White.it.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E02 - The House of Black and White.mkv
Shows/Game of Thrones/Season 05/Game of Thrones - S05E02 - The House of Black and White.nl.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E03 - High Sparrow.cs.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E03 - High Sparrow.de.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E03 - High Sparrow.en.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E03 - High Sparrow.es.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E03 - High Sparrow.fr.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E03 - High Sparrow.it.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E03 - High Sparrow.mp4
Shows/Game of Thrones/Season 05/Game of Thrones - S05E03 - High Sparrow.nl.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E04 - Sons of the Harpy.de.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E04 - Sons of the Harpy.en.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E04 - Sons of the Harpy.es.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E04 - Sons of the Harpy.fr.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E04 - Sons of the Harpy.it.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E04 - Sons of the Harpy.mp4
Shows/Game of Thrones/Season 05/Game of Thrones - S05E04 - Sons of the Harpy.nl.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E10 - Mother's Mercy.de.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E10 - Mother's Mercy.en.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E10 - Mother's Mercy.es.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E10 - Mother's Mercy.fr.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E10 - Mother's Mercy.it.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E10 - Mother's Mercy.mp4
Shows/Game of Thrones/Season 05/Game of Thrones - S05E10 - Mother's Mercy.nl.srt
miigotu@PC:~/Projects/SickRage $
```

**Comment by krash1220** [comment]
my subtitles are being downloaded to my SickRage folder and not under the tv show.
BRANCH: (master) / COMMIT: (508aad90bdf08b21877ecb93f73d93d023051727)

**Comment by krash1220** [comment]
No they are being downloaded to both places. But the ones under TV Shows are not being renamed correctly.
BRANCH: (master) / COMMIT: (508aad90bdf08b21877ecb93f73d93d023051727)

**Comment by miigotu** [comment]
@fernandog so should I keep trying to fix this stop hard linking it? Lol

Without hard linking most subtitles aren't found if they were renamed from the release_name

**Comment by miigotu** [comment]
@krash1220 have you just tried removing the incorrect ones and rescanning the show? Those may be leftover from and older commit.

**Comment by miigotu** [comment]
@krash1220 @matigonkas @abibouba I have removed the hard linking functionality. This was only for people who had renamed files in their library and needed better matches. 

It still finds subtitles for all of your items without this feature (if they exist), and it is less error prone.

If you have misnamed or mislocated subs anywhere just remove them, and either manual search for the subs, rescan the show, or wait for the subtitle downloader thread to figure it out for you.

@neoatomic I've also fixed the ui notification. It now is titles with the show name, and says `New subtitles downloaded: Language1, Language2`

**Comment by abibouba** [comment]
Hi @miigotu It still doesn't work. Subs are dowloaded but not renamed. FYI I'm on Ubuntu.   
Here is a log that may help you:
2015-07-12 10:35:04 ERROR    SHOWQUEUE-REFRESH :: 270633: Unable to modify date of True Detective s02e03 ASAP.mp4 to show air date juil. 05,2015 (21:00)
AAOSError: [Errno 1] Opération non permise: '/.../True Detective/Saison 02/True Detective s02e03 ASAP.mp4'
AA    os.utime(fname, (atime, atime))
AA  File "/.../.sickbeard/sickbeard/helpers.py", line 1248, in touchFile
AATraceback (most recent call last):
2015-07-12 10:35:04 ERROR    SHOWQUEUE-REFRESH :: File air date stamping failed. The error is: 1 and the message is: Opération non permise.
AANone

Access rights for the file and folders are correctly set.

**Comment by miigotu** [comment]
nonsense. Nothing even uses the release name anymore. I think your SUBTITLES_DIR is incorrectly set and you aren't seeing the ones that are actually downloaded.

There is no subtitle renaming done whatsover now.

Also, that error is unrelated to subtitles at all. Go in your post process settings and change
- [ ] Change File Date

**Comment by abibouba** [comment]
Nonsense ...

Let's take Extant s02e02. There are no subs.
![capture d ecran 2015-07-12 a 10 57 25](https://cloud.githubusercontent.com/assets/672894/8637187/2677406a-2885-11e5-80c2-47427fcbb172.png)

In the directory:
![capture d ecran 2015-07-12 a 10 58 03](https://cloud.githubusercontent.com/assets/672894/8637190/41e97b38-2885-11e5-8768-558b40768f51.png)

I then click on CC for that episode. A pop-up is displayed saying that no subtitles was found.
![capture d ecran 2015-07-12 a 11 02 16](https://cloud.githubusercontent.com/assets/672894/8637194/a7e78f6a-2885-11e5-80bb-92d4a738401b.png)


In the directory:
![capture d ecran 2015-07-12 a 10 59 02](https://cloud.githubusercontent.com/assets/672894/8637195/ae78d0fa-2885-11e5-8864-59b36e0e7ae1.png)

**Comment by miigotu** [comment]
Maybe you haven't updated? The fix was made on develop only.

I have just now updated master (which usually only happens 1 time a week).

**Comment by abibouba** [comment]
Do you store somewhere in db the filename before postprocessing? Seems to me that this original filename is used for the subtitle naming.

**Comment by miigotu** [comment]
No, it WAS done that way before my changes like 10 hours ago. Just update and try again.

**Comment by abibouba** [comment]
Yep it's fixed. Thanks.
Just didn't know I had to test with the dev branch.

**Comment by miigotu** [comment]
Cool, major changes only happen in develop to give them time to be tested before going to master, as soon as I knew it was fixed I was merging it to master =P

**Comment by fernandog** [comment]
@matigonkas can we close?

**Comment by matigonkas** [comment]
its now working, thanks @fernandog & @miigotu 
PS. its already closed (it got closed when migotu made the commit)

**Comment by matigonkas** [comment]
but there is something wierd happening some subtitles dont seem to be getting picked up by plex eventhough they are correctly named ,any one has clue as why this might be happening?

**Comment by fernandog** [comment]
permissions?!

**Comment by matigonkas** [comment]
@fernandog they all seem to have the same permissions , the ones detected by plex and the non detected

**Comment by fernandog** [comment]
check subtitle file encoding.

**Comment by matigonkas** [comment]
how do i do that? (on ubuntu server)

**Comment by fernandog** [comment]
@matigonkas kodi distinguish pt-pt subtitles from pt-br ? what about flex? do you know?
is there any flag in kodi about subtitles?

**Comment by matigonkas** [comment]
i do not use kodi only plex home teather (i believe its based on kodi/xbmc) ,about plex it detectes pt-pt correctly , pt-br does detect but shows them as unknown ,the ones that arent being detected are .pt and .en ,but at the same time it detectes some .pt & .en  correctly

**Comment by fernandog** [comment]
![1](https://cloud.githubusercontent.com/assets/2620870/8651103/58fa1c24-294d-11e5-8b83-aa763a99549c.png)

Kodi only DON'T recognize "pob".
all the other recognize correctly. 
pt and por recognizes as portuguese but not the dialect

**Comment by fernandog** [comment]
https://carousel.dropbox.com/photos/cc/CxvH1do1bIhq7qT

**Comment by miigotu** [comment]
what about .pb ?

**Comment by fernandog** [comment]
'unknown - pb (external)'

**Comment by fernandog** [comment]
so I would make pt-pt for Portugal and pt-br for Brazil

**Comment by miigotu** [comment]
I can't, we need to wait for that change in subliminal. For now, it will just be either pt-pt or pt-br (depending on which you selected, only select one) and it will be saved as .pt.srt

**Comment by miigotu** [comment]
This will work once my pr is ready.

**Comment by fernandog** [comment]
no problem IMO. not critical neither urgent. Just a naming thing. I'm sure @matigonkas agrees

**Comment by miigotu** [comment]
Its better than not being able to get pt-br in SR at all xD.

**Comment by matigonkas** [comment]
its ok to me , i speak pt-pt ,pt-br for me its like a fallback ,if it doesnt find pt-pt i will (almost) always have pt-br for my shows

**Comment by matigonkas** [comment]
@fernandog not sure if you help me but sr download this episode and the subs 
```
Burn Notice - S07E03 - Down Range.en.srt
Burn Notice - S07E03 - Down Range.mkv
Burn Notice - S07E03 - Down Range.pt-br.srt
Burn Notice - S07E03 - Down Range.pt-pt.srt
```
(the pt ones are rename manually ) 
the thing is non of this subs its being detected by plex while some others are

**Comment by fernandog** [comment]
@matigonkas try open with notepad++ if you are using windows.

**Comment by matigonkas** [comment]
@fernandog im not on windows but i can open them on a text file editor

**Comment by fernandog** [comment]
try to see the encoding of the file while opening

**Comment by matigonkas** [comment]
@fernandog 
somehow i believe i manage to get it working ,reinstalled plex ,deleted its plug-in folder (as if it where a fresh start) BUT while doing so i found that actually plex doesnt detect .pt-PT nor pt-BR language codes ,the only portuguese it detects is .pt (and the 3 letter code). .pb ,  .pob and pt-BR will appear as unknow

**Comment by Joshfindit** [comment]
Plex does only detect two-letter and three letter language codes.
Refer to [Adding Local Subtitles to Your Media](https://support.plex.tv/hc/en-us/articles/200471133-Adding-Local-Subtitles-to-Your-Media) (The section on External Subtitle Files)

**Comment by miigotu** [comment]
@Joshfindit the issue is specifically with pt-BR subs. Plex will only detect .pro and .pt as Portuguese, where there are different dialects of portuguese, specifically one for Brazil as in .pb , .pob and pt-BR, of which none are recognized by plex.

There are only a handful of languages that are not properly represented in ietf alpha2/alpha3 which must use an opensubtitles code

**Comment by Joshfindit** [comment]
@milgotu Until this thread, I wasn't aware that there were unique dialects that the 2 and 3 letter codes didn't cover.
It sounds like the best resolution long-term is by Plex supporting IETF codes.

**Comment by miigotu** [comment]
@Joshfindit it is already fixed in SR xD. we use opensubtitles codes, which is a set of alpha3 with a few added for the special case dialects. Plex should support this in the future, and Im not sure if kodi also has this issue or not.
