### ISSUE TITLE
ImportError: No module named resource causing too many redirects error after update

### ISSUE THREAD

**Issue by mattpulpfree** [SiCKRAGETV/sickrage-issues#2694]
On windows 7, master branch. c9729676cdbd2af5b04337b239bb3a843f5feaa4 
Story goes like this:
Saw that sickrage had some updates, did the git pull command and after a restart WebUI wouldn't load. did some searching and tried clearing out the cache folder, deleting failed,db, cache.db and sickbeard.db with not luck. Decided to delete all and start fresh, still didn't fix the issue. 

Here's the log file:
https://gist.github.com/mattpulpfree/83f69399e2d25407e3da#file-gistfile1-txt

**Comment by gatamah** [comment]
I am having the same problem.

**Comment by bitzorro** [comment]
Same here.

**Comment by wgbell** [comment]
Same here.

**Comment by OmgImAlexis** [comment]
Leave it a few minutes and then it'll work, this is a known issue.

**Comment by mattpulpfree** [comment]
it's been sitting there for over an hour now....still not working...

**Comment by OmgImAlexis** [comment]
@miigotu this may be a tvrage issue then.

**Comment by OmgImAlexis** [comment]
Are you guys all using this on Windows? This may be a Windows specific issue, most of the devs use linux for their testing.

**Comment by strike84** [comment]
Win 7 here, same problem.

**Comment by Plasticjesus690** [comment]
Same Issue here!

**Comment by OmgImAlexis** [comment]
@Plasticjesus690 @mattpulpfree @gatamah @bitzorro @wgbell 

What OS are you using? Windows?

**Comment by Plasticjesus690** [comment]
I am running it on server 2008. I have tired using clean copy of Master Build with no DB. I have also updated to latest version of python and installed mako. Everything works fine on all older versions of Sickrage.

**Comment by Jaerin** [comment]
Same issue as well on Windows 10

**Comment by OmgImAlexis** [comment]
@Plasticjesus690 we just merged 150+ commits, we know it's only this version that's why we're trying to workout what OS the bug is effecting so we can fix it. Looks like it may be a Windows specific issue.

**Comment by Plasticjesus690** [comment]
I understand that just figured it would be helpful to know that all the changes I have made do not effect your older commits from working.

**Comment by davidrot** [comment]
Same here Windows 7 64 bit, had 154 commits in updates.

**Comment by OmgImAlexis** [comment]
Alright. I think @neoatomic is looking into this.

**Comment by mattpulpfree** [comment]
Win 7 64 bit as well.

**Comment by bitzorro** [comment]
Windows 7 x86

**Comment by gatamah** [comment]
Windows 10 here

**Comment by aeror1** [comment]
Windows 7 64 here with the same issue, but its seems to me that the postprocessor is still running.

**Comment by PieterVO** [comment]
Windows 10, same issue

**Comment by koenrijpkema** [comment]
Windows 10 Pro x64, same issue

**Comment by TheMotto9** [comment]
Win 10 Home here. I would like to mention that although I am receiving this same error (This webpage has a redirect loop. ERR_TOO_MANY_REDIRECTS) SR still pulls new episodes and processes them as well.

**Comment by Kareltje71** [comment]
Same issue here with W8.1 X64, worked like a charm up till today.
Can we downgrade this version, and yes, how do I do this?

**Comment by pierre2013** [comment]
Same error, ERR_TOO_MANY_REDIRECTS

Windows 7

**Comment by danielmason30** [comment]
Windows 10 here.

**Comment by valkhyr1** [comment]
Same error on windows 2012R2.
I see the following lines in sickrage.log

2015-09-08 21:05:26 DEBUG    TORNADO :: Failed doing webui request "index": Traceback (most recent call last):
  File "E:\SickRage\sickbeard\webserve.py", line 257, in get
    results = yield self.async_call(method)
  File "E:\SickRage\tornado\gen.py", line 807, in run
    value = future.result()
  File "E:\SickRage\lib\concurrent\futures\_base.py", line 400, in result
    return self.__get_result()
  File "E:\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "E:\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "E:\SickRage\lib\concurrent\futures\thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\SickRage\sickbeard\webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "E:\SickRage\sickbeard\webserve.py", line 728, in index
    return t.render(title="Home", header="Show List", topmenu="home", showlists=showlists, submenu=self.HomeMenu())
  File "E:\SickRage\sickbeard\webserve.py", line 163, in render
    return super(PageTemplate, self).render(*args, **kwargs)
  File "E:\SickRage\lib\mako\template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "E:\SickRage\lib\mako\runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "E:\SickRage\lib\mako\runtime.py", line 834, in _render_context
    (inherit, lclcontext) = _populate_self_namespace(context, tmpl)
  File "E:\SickRage\lib\mako\runtime.py", line 780, in _populate_self_namespace
    ret = template.module._mako_inherit(template, context)
  File "E:\SickRage\cache\mako\SickRage\gui\slick\views\home.mako.py", line 69, in _mako_inherit
    return runtime._inherit_from(context, u'/layouts/main.mako', _template_uri)
  File "E:\SickRage\lib\mako\runtime.py", line 739, in _inherit_from
    template = _lookup_template(context, uri, calling_uri)
  File "E:\SickRage\lib\mako\runtime.py", line 769, in _lookup_template
    return lookup.get_template(uri)
  File "E:\SickRage\lib\mako\lookup.py", line 245, in get_template
    return self._load(srcfile, uri)
  File "E:\SickRage\lib\mako\lookup.py", line 311, in _load
    **self.template_args)
  File "E:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "E:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "E:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
  File "E:\SickRage\cache\mako\layouts\main.mako.py", line 23, in <module>
    import re, resource
ImportError: No module named resource

**Comment by thorismud** [comment]
Same Error, W10

**Comment by thorismud** [comment]
Traceback (most recent call last):
  File "c:\SickRage\sickbeard\webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "c:\SickRage\sickbeard\webserve.py", line 728, in index
    return t.render(title="Home", header="Show List", topmenu="home", showlists=showlists, submenu=self.HomeMenu())
  File "c:\SickRage\sickbeard\webserve.py", line 163, in render
    return super(PageTemplate, self).render(*args, **kwargs)
  File "c:\SickRage\lib\mako\template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "c:\SickRage\lib\mako\runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "c:\SickRage\lib\mako\runtime.py", line 834, in _render_context
    (inherit, lclcontext) = _populate_self_namespace(context, tmpl)
  File "c:\SickRage\lib\mako\runtime.py", line 780, in _populate_self_namespace
    ret = template.module._mako_inherit(template, context)
  File "c:\SickRage\cache\mako\SickRage\gui\slick\views\home.mako.py", line 69, in _mako_inherit
    return runtime._inherit_from(context, u'/layouts/main.mako', _template_uri)
  File "c:\SickRage\lib\mako\runtime.py", line 739, in _inherit_from
    template = _lookup_template(context, uri, calling_uri)
  File "c:\SickRage\lib\mako\runtime.py", line 769, in _lookup_template
    return lookup.get_template(uri)
  File "c:\SickRage\lib\mako\lookup.py", line 245, in get_template
    return self._load(srcfile, uri)
  File "c:\SickRage\lib\mako\lookup.py", line 311, in _load
    **self.template_args)
  File "c:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "c:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "c:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
  File "c:\SickRage\cache\mako\layouts\main.mako.py", line 23, in <module>
    import re, resource
ImportError: No module named resource
21:18:05 DEBUG::TORNADO :: Failed doing webui request "index": Traceback (most recent call last):
  File "c:\SickRage\sickbeard\webserve.py", line 257, in get
    results = yield self.async_call(method)
  File "c:\SickRage\tornado\gen.py", line 807, in run
    value = future.result()
  File "c:\SickRage\lib\concurrent\futures\_base.py", line 400, in result
    return self.__get_result()
  File "c:\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "c:\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "c:\SickRage\lib\concurrent\futures\thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\SickRage\sickbeard\webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "c:\SickRage\sickbeard\webserve.py", line 728, in index
    return t.render(title="Home", header="Show List", topmenu="home", showlists=showlists, submenu=self.HomeMenu())
  File "c:\SickRage\sickbeard\webserve.py", line 163, in render
    return super(PageTemplate, self).render(*args, **kwargs)
  File "c:\SickRage\lib\mako\template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "c:\SickRage\lib\mako\runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "c:\SickRage\lib\mako\runtime.py", line 834, in _render_context
    (inherit, lclcontext) = _populate_self_namespace(context, tmpl)
  File "c:\SickRage\lib\mako\runtime.py", line 780, in _populate_self_namespace
    ret = template.module._mako_inherit(template, context)
  File "c:\SickRage\cache\mako\SickRage\gui\slick\views\home.mako.py", line 69, in _mako_inherit
    return runtime._inherit_from(context, u'/layouts/main.mako', _template_uri)
  File "c:\SickRage\lib\mako\runtime.py", line 739, in _inherit_from
    template = _lookup_template(context, uri, calling_uri)
  File "c:\SickRage\lib\mako\runtime.py", line 769, in _lookup_template
    return lookup.get_template(uri)
  File "c:\SickRage\lib\mako\lookup.py", line 245, in get_template
    return self._load(srcfile, uri)
  File "c:\SickRage\lib\mako\lookup.py", line 311, in _load
    **self.template_args)
  File "c:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "c:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "c:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
  File "c:\SickRage\cache\mako\layouts\main.mako.py", line 23, in <module>
    import re, resource
ImportError: No module named resource

**Comment by neoatomic** [comment]
Rollback would be possible.  But i advice to wait, think with 6-12 hours the fix should be on Master. So just hang on a little, i'm sure you all survive a few hours without SickRage right.? :) 

Also check your backup folder and copy the zip files to a safe place, just in case you need them to restore.

```
git reset --hard
git checkout -- .
git checkout -b tag4054 v4.0.54
```

**Comment by pierre2013** [comment]
Noooooooooo!!!!!! 6 - 12 hours without SickRage!!!!!????? How will I survive??? what to do? what to do? ;D

**Comment by Omniback** [comment]
Windows 8.1 here also having those issues

**Comment by kotysoft** [comment]
Probably updated automatically for me, because same issue occurs when I came home.

## SYSTEM
Windows 2008 R2 Server HUN
SR User: "Rendszergazda" (administrator)
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
 [LOG on pastebin](http://pastebin.com/F623NW5f)

**Comment by jkadivnik** [comment]
I have the same issue.
Some testing pointed to commit 73b3c3e4d2d62b31cec07fdcdff76ab48723366d being the issue (missed import, fixup conditions). 
If I perform a hard reset to the commit before that one everything seems to work okay.

    git reset --hard b2af183ad3bb07c8f416f83be96195425f2abd5d

Hope this helps in narrowing down the issue.

OS is windows 2012

**Comment by miigotu** [comment]
easy fix. I'll fix it when I'm at a PC if none else has.

**Comment by autronix** [comment]
Same issue here with Windows 8

**Comment by MGaetan89** [comment]
A fix has been pushed to `master` to address this issue.
Let us know if it fixes it for you.

**Comment by Jaerin** [comment]
Working for me

**Comment by aeror1** [comment]
For the git challenged like myself, how do we update this?  Thanks.

**Comment by Mosalar** [comment]
Working here as well. Kudos for the fast fix.

**Comment by neoatomic** [comment]
@aeror1 Its actually pretty easy.

```
Stop SickRage, SSH(Linux)/CMD(Windows) and enter SickRage folder

git remote add upstream https://github.com/SiCKRAGETV/SickRage.git
git fetch upstream
git checkout master
git branch -u upstream/master
git reset --hard upstream/master
git pull
```

If that doesn't work you could manually overwrite the files.

gui/slick/views/layouts/main.mako
gui/slick/views/inc_bottom.mako
gui/slick/views/inc_top.mako

(get them from this zip)
https://github.com/SiCKRAGETV/SickRage/archive/master.zip

After SickRage starts again than enable the below function to ensure that GIT corrects/resets your files.

```
Go to SickRage Settings > General > Advanced > Github and enable this setting:

Git reset (removes untracked files and performs a hard reset on git branch automatically to help resolve update issues)
```

**Comment by miigotu** [comment]
```
gui/slick/views/inc_bottom.mako
gui/slick/views/inc_top.mako
```
Those were actually deleted ^

**Comment by kerbysj** [comment]
i removed below and then replaced main.mako yet still getting the below error. any ideas?
gui/slick/views/inc_bottom.mako
gui/slick/views/inc_top.mako

 File "SickBeard.py", line 522, in <module>
    SickRage().start()
  File "SickBeard.py", line 295, in start
    sickbeard.initialize(consoleLogging=self.consoleLogging)
  File "/apps/sickbeard/sickbeard/__init__.py", line 1308, in initialize
    db.sanityCheckDatabase(myDB, mainDB.MainSanityCheck)
  File "/apps/sickbeard/sickbeard/db.py", line 254, in sanityCheckDatabase
    sanity_check(connection).check()
  File "/apps/sickbeard/sickbeard/databases/mainDB.py", line 46, in check
    self.convert_tvrage_to_tvdb()
  File "/apps/sickbeard/sickbeard/databases/mainDB.py", line 77, in convert_tvrage_to_tvdb
    (INDEXER_TVDB, mapping[0]['mindexer_id'], tvrage_show['indexer_id'])
  File "/apps/sickbeard/sickbeard/db.py", line 168, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/apps/sickbeard/sickbeard/db.py", line 88, in execute
    return self._execute(query, args)
  File "/apps/sickbeard/sickbeard/db.py", line 76, in _execute
    return self.connection.cursor().execute(query)
sqlite3.IntegrityError: UNIQUE constraint failed: tv_shows.indexer_id

**Comment by Vodka2014** [comment]
So i take this for a Synology user i just log in as ROOT/ADMIN and run the commands ?

**Comment by gerbil42** [comment]
I ran a git pull to get the update from Master and SickRage now starts. Yay!
However, there were 5 shows that were from TVRage indexer that weren't able to be migrated. 

They remained in the show list.  If you clicked on them to open the episode list/properties page, an error was generated in the logs (I no longer have this in the UI)

On startup - this happens:
2015-09-08 15:31:39 INFO     MAIN :: 24656: Unable to find IMDb show info in the database
2015-09-08 15:31:39 INFO     MAIN :: 1563: Unable to find IMDb show info in the database
2015-09-08 15:31:39 INFO     MAIN :: 7023: Unable to find IMDb show info in the database
2015-09-08 15:31:39 INFO     MAIN :: 29772: Unable to find IMDb show info in the database
2015-09-08 15:31:39 INFO     MAIN :: 287134: Unable to find IMDb show info in the database
2015-09-08 15:31:39 WARNING  MAIN :: Error mapping show from tvrage to tvdb for NFL Thursday Night Football, found 0 results. This show will no longer update!
2015-09-08 15:31:39 WARNING  MAIN :: Error mapping show from tvrage to tvdb for Monday Night Football, found 0 results. This show will no longer update!
2015-09-08 15:31:39 WARNING  MAIN :: Error mapping show from tvrage to tvdb for NBC Sunday Night Football, found 0 results. This show will no longer update!
2015-09-08 15:31:39 WARNING  MAIN :: Error mapping show from tvrage to tvdb for NFL on CBS, found 0 results. This show will no longer update!
2015-09-08 15:31:39 WARNING  MAIN :: Found 4 shows with TVRage ID', FIXING!
2015-09-08 15:31:39 INFO     MAIN :: Checking for shows with tvrage id's, since tvrage is gone

When trying to remove all 5 with Mass Update, I hit this exception on each.
2015-09-08 15:28:26 INFO     SHOWQUEUE-REMOVE-SHOW :: Attempt to delete cache file D:\SickRage\cache\images\8197.fanart.jpg
2015-09-08 15:28:26 INFO     SHOWQUEUE-REMOVE-SHOW :: Removing NFL on FOX
AA
AATypeError: argument of type 'int' is not iterable
AA    return show.indexerid in [x.show.indexerid for x in self.queue if x.action_id in actions]
AA  File "D:\SickRage\sickbeard\show_queue.py", line 44, in _isInQueue
AA    if self._isInQueue(show, ShowQueueActions.REMOVE):
AA  File "D:\SickRage\sickbeard\show_queue.py", line 154, in removeShow
AA    sickbeard.showQueueScheduler.action.removeShow(showObj)
AA  File "D:\SickRage\sickbeard\webserve.py", line 3384, in massUpdate
AA    result = function(**kwargs)
AA  File "D:\SickRage\sickbeard\webserve.py", line 272, in async_call
AA    result = self.fn(*self.args, **self.kwargs)
AA  File "D:\SickRage\lib\concurrent\futures\thread.py", line 61, in run
AA    exec('raise exc_type, exc_value, traceback', {}, locals_)
AA  File "D:\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise
AA    reraise(self._exception, self._traceback)
AA  File "D:\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result
AA    return self.__get_result()
AA  File "D:\SickRage\lib\concurrent\futures\_base.py", line 400, in result
AA    value = future.result()
AA  File "D:\SickRage\tornado\gen.py", line 807, in run
AA    results = yield self.async_call(method)
AA  File "D:\SickRage\sickbeard\webserve.py", line 257, in get
AATypeError: argument of type 'int' is not iterable
AA    return show.indexerid in [x.show.indexerid for x in self.queue if x.action_id in actions]
AA  File "D:\SickRage\sickbeard\show_queue.py", line 44, in _isInQueue
AA    if self._isInQueue(show, ShowQueueActions.REMOVE):
AA  File "D:\SickRage\sickbeard\show_queue.py", line 154, in removeShow
AA    sickbeard.showQueueScheduler.action.removeShow(showObj)
AA  File "D:\SickRage\sickbeard\webserve.py", line 3384, in massUpdate
AA    result = function(**kwargs)
AA  File "D:\SickRage\sickbeard\webserve.py", line 272, in async_call
AATraceback (most recent call last):
AATypeError: argument of type 'int' is not iterable
AA    return show.indexerid in [x.show.indexerid for x in self.queue if x.action_id in actions]
AA  File "D:\SickRage\sickbeard\show_queue.py", line 44, in _isInQueue
AA    if self._isInQueue(show, ShowQueueActions.REMOVE):
AA  File "D:\SickRage\sickbeard\show_queue.py", line 154, in removeShow
AA    sickbeard.showQueueScheduler.action.removeShow(showObj)
AA  File "D:\SickRage\sickbeard\webserve.py", line 3384, in massUpdate
AA    result = function(**kwargs)
AA  File "D:\SickRage\sickbeard\webserve.py", line 272, in async_call
2015-09-08 15:28:24 ERROR    Thread-25 :: Failed doing webui callback: Traceback (most recent call last):
AA
AAKeyError: 2
AA    return indexerConfig[self.indexerID]['name']
AA  File "D:\SickRage\sickbeard\indexers\indexer_api.py", line 49, in name
AA    u'Looking up XEM scene mapping for show %s on %s' % (indexer_id, sickbeard.indexerApi(indexer).name,),
AA  File "D:\SickRage\sickbeard\scene_numbering.py", line 480, in xem_refresh
AA    xem_refresh(indexer_id, indexer)
AA  File "D:\SickRage\sickbeard\scene_numbering.py", line 380, in get_xem_numbering_for_show
AA    xem_numbering=get_xem_numbering_for_show(indexerid, indexer),
AA  File "D:\SickRage\sickbeard\webserve.py", line 1295, in displayShow
AA    result = function(**kwargs)
AA  File "D:\SickRage\sickbeard\webserve.py", line 272, in async_call
AA    result = self.fn(*self.args, **self.kwargs)
AA  File "D:\SickRage\lib\concurrent\futures\thread.py", line 61, in run
AA    exec('raise exc_type, exc_value, traceback', {}, locals_)
AA  File "D:\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise
AA    reraise(self._exception, self._traceback)
AA  File "D:\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result
AA    return self.__get_result()
AA  File "D:\SickRage\lib\concurrent\futures\_base.py", line 400, in result
AA    value = future.result()
AA  File "D:\SickRage\tornado\gen.py", line 807, in run
AA    results = yield self.async_call(method)
AA  File "D:\SickRage\sickbeard\webserve.py", line 257, in get

The shows would disappear from the list, but come back each restart.
Had to remove 1 at a time, restart, rinse, repeat.

**Comment by miigotu** [comment]
@kerbysj seems just restarting it at that point should fix that last issue, have you tried that? I need to reorder the db sanity checks to avoid this.

@gerbil42 Ill look into fixing mass remove later.

**Comment by Vodka2014** [comment]
I cannot run git via Putty get not found and i am connected to my Synology NAS as root

**Comment by neoatomic** [comment]
@Vodka2014 You need to run those commands inside the folder where the config.ini is located. that should be `/volume1/@appstore/sickrage/var`

If that doesn't work than backup the config.ini and sickbeard.db and remove/reinstall the package from the package center.

**Comment by TheMotto9** [comment]
SR is back but my shows are missing cover art and all of my network images are back to plain text. Is this normal?

**Comment by Vodka2014** [comment]
@neoatomic Well here goes nothing as i still get  
-sh: git: not found
time to try and back this all up thanks

**Comment by neoatomic** [comment]
@TheMotto9 Go to Mass Update and select `Update` for all shows. Then the Banners will be downloaded. (The Network logos are currently not working.)

**Comment by Vodka2014** [comment]
I noticed that these files are not in that ZIP file of the Master:
gui/slick/views/inc_bottom.mako
gui/slick/views/inc_top.mako

**Comment by Vodka2014** [comment]
@neoatomic So i re-install and i found that once i moved the DB back over it was the issue so i just had my configs. all working. Now i have to add all my shows back again.

On the Notification Section i got the below error: 

<div class="component-group-desc"> <img class="notifier-icon" src="${sbRoot}/images/notifiers/kodi.png" alt="" title="KODI" /> <h3><a href="${anon_url('http://kodi.tv/')}" rel="noreferrer" onclick="window.open(this.href, '_blank'); return false;">KODI</a></h3> <p>A free and open source cross-platform media center and home entertainment system software with a 10-foot user interface designed for the living-room TV.</p> </div> <fieldset class="component-group-list"> <div class="field-pair"> <label class="clearfix" for="use_kodi">
/usr/local/sickrage/var/SickRage/gui/slick/views/config_notifications.mako, line 39:
<h3><a href="${anon_url('http://kodi.tv/')}" rel="noreferrer" onclick="window.open(this.href, '_blank'); return false;">KODI</a></h3>
/usr/local/sickrage/var/SickRage/gui/slick/views/layouts/main.mako, line 217:
/usr/local/sickrage/var/SickRage/lib/mako/runtime.py, line 853:
callable_(context, *args, **kwargs)

**Comment by aeror1** [comment]
@neoatomic thanks for the steps!  it worked.  The banners are missing so i did an update like you mentioned, so im waiting on that.  What i did notice is that after doing the steps and getting the GUI backup, SR is much slower to load the home page with the shows.  any idea?  thanks.

**Comment by TheMotto9** [comment]
@neoatomic & @miigotu (when you awake) ... I did a mass update on all of my shows and I also attempted to restart my PC. But, I am still without Posters for all of my TV shows. Obviously you guys seem to have bigger fish to fry but I figured I'd let you know that the mass update did NOT work.

**Comment by pierre2013** [comment]
@neoatomic 

Doing the git pull, I get already up-to-date. trying manual now

**Comment by pierre2013** [comment]
@neoatomic 

inc_bottom.mako and inc_top.mako is missing from the zip provided.

**Comment by pierre2013** [comment]
mine started up now, but no banner or nothing, and this is returned in the logs.Idid do a mass update.

AA
AAImportError: No module named resource
AA    import re, resource
AA  File "c:\Sickrage\cache\mako\layouts\main.mako.py", line 23, in 
AA    return imp.load_source(module_id, path, fp)
AA  File "c:\Sickrage\lib\mako\compat.py", line 66, in load_module
AA    module = compat.load_module(self.module_id, path)
AA  File "c:\Sickrage\lib\mako\template.py", line 379, in _compile_from_file
AA    module = self._compile_from_file(path, filename)
AA  File "c:\Sickrage\lib\mako\template.py", line 321, in __init__
AA    **self.template_args)
AA  File "c:\Sickrage\lib\mako\lookup.py", line 311, in _load
AA    return self._load(srcfile, uri)
AA  File "c:\Sickrage\lib\mako\lookup.py", line 245, in get_template
AA    return lookup.get_template(uri)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 769, in _lookup_template
AA    template = _lookup_template(context, uri, calling_uri)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 739, in _inherit_from
AA    return runtime._inherit_from(context, u'/layouts/main.mako', _template_uri)
AA  File "c:\Sickrage\cache\mako\Sickrage\gui\slick\views\home.mako.py", line 69, in _mako_inherit
AA    ret = template.module._mako_inherit(template, context)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 780, in _populate_self_namespace
AA    (inherit, lclcontext) = _populate_self_namespace(context, tmpl)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 834, in _render_context
AA    **_kwargs_for_callable(callable_, data))
AA  File "c:\Sickrage\lib\mako\runtime.py", line 803, in _render
AA    return runtime._render(self, self.callable_, args, data)
AA  File "c:\Sickrage\lib\mako\template.py", line 443, in render
AA    return super(PageTemplate, self).render(*args, **kwargs)
AA  File "c:\Sickrage\sickbeard\webserve.py", line 163, in render
AA    return t.render(title="Home", header="Show List", topmenu="home", showlists=showlists, submenu=self.HomeMenu())
AA  File "c:\Sickrage\sickbeard\webserve.py", line 728, in index
AA    result = function(**kwargs)
AA  File "c:\Sickrage\sickbeard\webserve.py", line 272, in async_call
AA    result = self.fn(*self.args, **self.kwargs)
AA  File "c:\Sickrage\lib\concurrent\futures\thread.py", line 61, in run
AA    exec('raise exc_type, exc_value, traceback', {}, locals_)
AA  File "c:\Sickrage\lib\concurrent\futures\_compat.py", line 107, in reraise
AA    reraise(self._exception, self._traceback)
AA  File "c:\Sickrage\lib\concurrent\futures\_base.py", line 359, in __get_result
AA    return self.__get_result()
AA  File "c:\Sickrage\lib\concurrent\futures\_base.py", line 400, in result
AA    value = future.result()
AA  File "c:\Sickrage\tornado\gen.py", line 807, in run
AA    results = yield self.async_call(method)
AA  File "c:\Sickrage\sickbeard\webserve.py", line 257, in get
AAImportError: No module named resource
AA    import re, resource
AA  File "c:\Sickrage\cache\mako\layouts\main.mako.py", line 23, in 
AA    return imp.load_source(module_id, path, fp)
AA  File "c:\Sickrage\lib\mako\compat.py", line 66, in load_module
AA    module = compat.load_module(self.module_id, path)
AA  File "c:\Sickrage\lib\mako\template.py", line 379, in _compile_from_file
AA    module = self._compile_from_file(path, filename)
AA  File "c:\Sickrage\lib\mako\template.py", line 321, in __init__
AA    **self.template_args)
AA  File "c:\Sickrage\lib\mako\lookup.py", line 311, in _load
AA    return self._load(srcfile, uri)
AA  File "c:\Sickrage\lib\mako\lookup.py", line 245, in get_template
AA    return lookup.get_template(uri)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 769, in _lookup_template
AA    template = _lookup_template(context, uri, calling_uri)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 739, in _inherit_from
AA    return runtime._inherit_from(context, u'/layouts/main.mako', _template_uri)
AA  File "c:\Sickrage\cache\mako\Sickrage\gui\slick\views\home.mako.py", line 69, in _mako_inherit
AA    ret = template.module._mako_inherit(template, context)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 780, in _populate_self_namespace
AA    (inherit, lclcontext) = _populate_self_namespace(context, tmpl)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 834, in _render_context
AA    **_kwargs_for_callable(callable_, data))
AA  File "c:\Sickrage\lib\mako\runtime.py", line 803, in _render
AA    return runtime._render(self, self.callable_, args, data)
AA  File "c:\Sickrage\lib\mako\template.py", line 443, in render
AA    return super(PageTemplate, self).render(*args, **kwargs)
AA  File "c:\Sickrage\sickbeard\webserve.py", line 163, in render
AA    return t.render(title="Home", header="Show List", topmenu="home", showlists=showlists, submenu=self.HomeMenu())
AA  File "c:\Sickrage\sickbeard\webserve.py", line 728, in index
AA    result = function(**kwargs)
AA  File "c:\Sickrage\sickbeard\webserve.py", line 272, in async_call
AATraceback (most recent call last):
AAImportError: No module named resource
AA    import re, resource
AA  File "c:\Sickrage\cache\mako\layouts\main.mako.py", line 23, in 
AA    return imp.load_source(module_id, path, fp)
AA  File "c:\Sickrage\lib\mako\compat.py", line 66, in load_module
AA    module = compat.load_module(self.module_id, path)
AA  File "c:\Sickrage\lib\mako\template.py", line 379, in _compile_from_file
AA    module = self._compile_from_file(path, filename)
AA  File "c:\Sickrage\lib\mako\template.py", line 321, in __init__
AA    **self.template_args)
AA  File "c:\Sickrage\lib\mako\lookup.py", line 311, in _load
AA    return self._load(srcfile, uri)
AA  File "c:\Sickrage\lib\mako\lookup.py", line 245, in get_template
AA    return lookup.get_template(uri)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 769, in _lookup_template
AA    template = _lookup_template(context, uri, calling_uri)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 739, in _inherit_from
AA    return runtime._inherit_from(context, u'/layouts/main.mako', _template_uri)
AA  File "c:\Sickrage\cache\mako\Sickrage\gui\slick\views\home.mako.py", line 69, in _mako_inherit
AA    ret = template.module._mako_inherit(template, context)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 780, in _populate_self_namespace
AA    (inherit, lclcontext) = _populate_self_namespace(context, tmpl)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 834, in _render_context
AA    **_kwargs_for_callable(callable_, data))
AA  File "c:\Sickrage\lib\mako\runtime.py", line 803, in _render
AA    return runtime._render(self, self.callable_, args, data)
AA  File "c:\Sickrage\lib\mako\template.py", line 443, in render
AA    return super(PageTemplate, self).render(*args, **kwargs)
AA  File "c:\Sickrage\sickbeard\webserve.py", line 163, in render
AA    return t.render(title="Home", header="Show List", topmenu="home", showlists=showlists, submenu=self.HomeMenu())
AA  File "c:\Sickrage\sickbeard\webserve.py", line 728, in index
AA    result = function(**kwargs)
AA  File "c:\Sickrage\sickbeard\webserve.py", line 272, in async_call
2015-09-09 06:39:25 ERROR    Thread-26 :: Failed doing webui callback: Traceback (most recent call last):
AA
AAImportError: No module named resource
AA    import re, resource
AA  File "c:\Sickrage\cache\mako\layouts\main.mako.py", line 23, in 
AA    return imp.load_source(module_id, path, fp)
AA  File "c:\Sickrage\lib\mako\compat.py", line 66, in load_module
AA    module = compat.load_module(self.module_id, path)
AA  File "c:\Sickrage\lib\mako\template.py", line 379, in _compile_from_file
AA    module = self._compile_from_file(path, filename)
AA  File "c:\Sickrage\lib\mako\template.py", line 321, in __init__
AA    **self.template_args)
AA  File "c:\Sickrage\lib\mako\lookup.py", line 311, in _load
AA    return self._load(srcfile, uri)
AA  File "c:\Sickrage\lib\mako\lookup.py", line 245, in get_template
AA    return lookup.get_template(uri)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 769, in _lookup_template
AA    template = _lookup_template(context, uri, calling_uri)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 739, in _inherit_from
AA    return runtime._inherit_from(context, u'/layouts/main.mako', _template_uri)
AA  File "c:\Sickrage\cache\mako\Sickrage\gui\slick\views\home.mako.py", line 69, in _mako_inherit
AA    ret = template.module._mako_inherit(template, context)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 780, in _populate_self_namespace
AA    (inherit, lclcontext) = _populate_self_namespace(context, tmpl)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 834, in _render_context
AA    **_kwargs_for_callable(callable_, data))
AA  File "c:\Sickrage\lib\mako\runtime.py", line 803, in _render
AA    return runtime._render(self, self.callable_, args, data)
AA  File "c:\Sickrage\lib\mako\template.py", line 443, in render
AA    return super(PageTemplate, self).render(*args, **kwargs)
AA  File "c:\Sickrage\sickbeard\webserve.py", line 163, in render
AA    return t.render(title="Home", header="Show List", topmenu="home", showlists=showlists, submenu=self.HomeMenu())
AA  File "c:\Sickrage\sickbeard\webserve.py", line 728, in index
AA    result = function(**kwargs)
AA  File "c:\Sickrage\sickbeard\webserve.py", line 272, in async_call
AA    result = self.fn(*self.args, **self.kwargs)
AA  File "c:\Sickrage\lib\concurrent\futures\thread.py", line 61, in run
AA    exec('raise exc_type, exc_value, traceback', {}, locals_)
AA  File "c:\Sickrage\lib\concurrent\futures\_compat.py", line 107, in reraise
AA    reraise(self._exception, self._traceback)
AA  File "c:\Sickrage\lib\concurrent\futures\_base.py", line 359, in __get_result
AA    return self.__get_result()
AA  File "c:\Sickrage\lib\concurrent\futures\_base.py", line 400, in result
AA    value = future.result()
AA  File "c:\Sickrage\tornado\gen.py", line 807, in run
AA    results = yield self.async_call(method)
AA  File "c:\Sickrage\sickbeard\webserve.py", line 257, in get
AAImportError: No module named resource
AA    import re, resource
AA  File "c:\Sickrage\cache\mako\layouts\main.mako.py", line 23, in 
AA    return imp.load_source(module_id, path, fp)
AA  File "c:\Sickrage\lib\mako\compat.py", line 66, in load_module
AA    module = compat.load_module(self.module_id, path)
AA  File "c:\Sickrage\lib\mako\template.py", line 379, in _compile_from_file
AA    module = self._compile_from_file(path, filename)
AA  File "c:\Sickrage\lib\mako\template.py", line 321, in __init__
AA    **self.template_args)
AA  File "c:\Sickrage\lib\mako\lookup.py", line 311, in _load
AA    return self._load(srcfile, uri)
AA  File "c:\Sickrage\lib\mako\lookup.py", line 245, in get_template
AA    return lookup.get_template(uri)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 769, in _lookup_template
AA    template = _lookup_template(context, uri, calling_uri)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 739, in _inherit_from
AA    return runtime._inherit_from(context, u'/layouts/main.mako', _template_uri)
AA  File "c:\Sickrage\cache\mako\Sickrage\gui\slick\views\home.mako.py", line 69, in _mako_inherit
AA    ret = template.module._mako_inherit(template, context)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 780, in _populate_self_namespace
AA    (inherit, lclcontext) = _populate_self_namespace(context, tmpl)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 834, in _render_context
AA    **_kwargs_for_callable(callable_, data))
AA  File "c:\Sickrage\lib\mako\runtime.py", line 803, in _render
AA    return runtime._render(self, self.callable_, args, data)
AA  File "c:\Sickrage\lib\mako\template.py", line 443, in render
AA    return super(PageTemplate, self).render(*args, **kwargs)
AA  File "c:\Sickrage\sickbeard\webserve.py", line 163, in render
AA    return t.render(title="Home", header="Show List", topmenu="home", showlists=showlists, submenu=self.HomeMenu())
AA  File "c:\Sickrage\sickbeard\webserve.py", line 728, in index
AA    result = function(**kwargs)
AA  File "c:\Sickrage\sickbeard\webserve.py", line 272, in async_call
AATraceback (most recent call last):
AAImportError: No module named resource
AA    import re, resource
AA  File "c:\Sickrage\cache\mako\layouts\main.mako.py", line 23, in 
AA    return imp.load_source(module_id, path, fp)
AA  File "c:\Sickrage\lib\mako\compat.py", line 66, in load_module
AA    module = compat.load_module(self.module_id, path)
AA  File "c:\Sickrage\lib\mako\template.py", line 379, in _compile_from_file
AA    module = self._compile_from_file(path, filename)
AA  File "c:\Sickrage\lib\mako\template.py", line 321, in __init__
AA    **self.template_args)
AA  File "c:\Sickrage\lib\mako\lookup.py", line 311, in _load
AA    return self._load(srcfile, uri)
AA  File "c:\Sickrage\lib\mako\lookup.py", line 245, in get_template
AA    return lookup.get_template(uri)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 769, in _lookup_template
AA    template = _lookup_template(context, uri, calling_uri)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 739, in _inherit_from
AA    return runtime._inherit_from(context, u'/layouts/main.mako', _template_uri)
AA  File "c:\Sickrage\cache\mako\Sickrage\gui\slick\views\home.mako.py", line 69, in _mako_inherit
AA    ret = template.module._mako_inherit(template, context)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 780, in _populate_self_namespace
AA    (inherit, lclcontext) = _populate_self_namespace(context, tmpl)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 834, in _render_context
AA    **_kwargs_for_callable(callable_, data))
AA  File "c:\Sickrage\lib\mako\runtime.py", line 803, in _render
AA    return runtime._render(self, self.callable_, args, data)
AA  File "c:\Sickrage\lib\mako\template.py", line 443, in render
AA    return super(PageTemplate, self).render(*args, **kwargs)
AA  File "c:\Sickrage\sickbeard\webserve.py", line 163, in render
AA    return t.render(title="Home", header="Show List", topmenu="home", showlists=showlists, submenu=self.HomeMenu())
AA  File "c:\Sickrage\sickbeard\webserve.py", line 728, in index
AA    result = function(**kwargs)
AA  File "c:\Sickrage\sickbeard\webserve.py", line 272, in async_call
2015-09-09 06:39:25 ERROR    Thread-21 :: Failed doing webui callback: Traceback (most recent call last):
AA
AAImportError: No module named resource
AA    import re, resource
AA  File "c:\Sickrage\cache\mako\layouts\main.mako.py", line 23, in 
AA    return imp.load_source(module_id, path, fp)
AA  File "c:\Sickrage\lib\mako\compat.py", line 66, in load_module
AA    module = compat.load_module(self.module_id, path)
AA  File "c:\Sickrage\lib\mako\template.py", line 379, in _compile_from_file
AA    module = self._compile_from_file(path, filename)
AA  File "c:\Sickrage\lib\mako\template.py", line 321, in __init__
AA    **self.template_args)
AA  File "c:\Sickrage\lib\mako\lookup.py", line 311, in _load
AA    return self._load(srcfile, uri)
AA  File "c:\Sickrage\lib\mako\lookup.py", line 245, in get_template
AA    return lookup.get_template(uri)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 769, in _lookup_template
AA    template = _lookup_template(context, uri, calling_uri)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 739, in _inherit_from
AA    return runtime._inherit_from(context, u'/layouts/main.mako', _template_uri)
AA  File "c:\Sickrage\cache\mako\Sickrage\gui\slick\views\home.mako.py", line 69, in _mako_inherit
AA    ret = template.module._mako_inherit(template, context)
AA  File "c:\Sickrage\lib\mako\runtime.py", line 780, in _populate_self_namespace
AA    (inherit, lclcontext) = _populate_self_namespace(context, tmpl)

**Comment by MGaetan89** [comment]
Missing images are tracked in #2708
This issue (#2694) has been fixed already.
