### ISSUE TITLE
Update unsuccessful

### ISSUE THREAD

**Issue by loungebob** [SiCKRAGETV/sickrage-issues#2722]
Well, maybe. SR keeps flashing notifications saying Update Successful but when reloading it, it tells me I'm 23 commits behind and should update. Here's the error log:
```
2015-09-09 15:41:08 INFO     Thread-13 :: Moving files from F:\Mediaserver\SickRage\sr-update\SiCKRAGETV-SickRage-9edd012 to F:\Mediaserver\SickRage
2015-09-09 15:41:08 INFO     Thread-13 :: Deleting file F:\Mediaserver\SickRage\sr-update\sr-update.tar
2015-09-09 15:41:00 INFO     Thread-13 :: Extracting file F:\Mediaserver\SickRage\sr-update\sr-update.tar
2015-09-09 15:40:57 INFO     Thread-13 :: Downloading update from 'http://github.com/SiCKRAGETV/SickRage/tarball/master'
2015-09-09 15:40:57 INFO     Thread-13 :: Creating update folder F:\Mediaserver\SickRage\sr-update before extracting
2015-09-09 15:40:57 INFO     Thread-13 :: Clearing out update folder F:\Mediaserver\SickRage\sr-update before extracting
2015-09-09 15:40:57 INFO     Thread-13 :: Config backup successful, updating...
2015-09-09 15:40:27 INFO     Thread-13 :: Config backup in progress...
2015-09-09 15:40:02 ERROR    EVENT-QUEUE :: Exception generated in thread EVENT-QUEUE: near "WHERE": syntax error
AAOperationalError: near "WHERE": syntax error
AA    return self.connection.cursor().execute(query, args)
AA  File "F:\Mediaserver\SickRage\sickbeard\db.py", line 77, in _execute
AA    return self._execute(query, args)
AA  File "F:\Mediaserver\SickRage\sickbeard\db.py", line 88, in execute
AA    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
AA  File "F:\Mediaserver\SickRage\sickbeard\db.py", line 168, in action
AATraceback (most recent call last):
2015-09-09 15:40:02 ERROR    EVENT-QUEUE :: DB error: near "WHERE": syntax error
2015-09-09 15:40:01 INFO     EVENT-QUEUE :: Saving all shows to the database
2015-09-09 15:40:00 INFO     EVENT-QUEUE :: Waiting for the SUBTITLESFINDER thread to exit
2015-09-09 15:40:00 INFO     EVENT-QUEUE :: Waiting for the PROPERFINDER thread to exit
2015-09-09 15:39:59 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2015-09-09 15:39:58 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSER thread to exit
2015-09-09 15:39:57 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE thread to exit
2015-09-09 15:39:57 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE thread to exit
2015-09-09 15:39:56 INFO     EVENT-QUEUE :: Waiting for the VERSIONCHECKER thread to exit
2015-09-09 15:39:55 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2015-09-09 15:39:54 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2015-09-09 15:39:54 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCH thread to exit
2015-09-09 15:39:54 INFO     EVENT-QUEUE :: Waiting for the EVENTS thread to exit
2015-09-09 15:39:54 INFO     EVENT-QUEUE :: Aborting all threads
2015-09-09 15:39:54 INFO     CHECKVERSION :: Update was successful!
2015-09-09 15:39:47 INFO     CHECKVERSION :: Moving files from F:\Mediaserver\SickRage\sr-update\SiCKRAGETV-SickRage-9edd012 to F:\Mediaserver\SickRage
2015-09-09 15:39:47 INFO     CHECKVERSION :: Deleting file F:\Mediaserver\SickRage\sr-update\sr-update.tar
2015-09-09 15:39:37 INFO     CHECKVERSION :: Extracting file F:\Mediaserver\SickRage\sr-update\sr-update.tar
2015-09-09 15:39:34 INFO     CHECKVERSION :: Downloading update from 'http://github.com/SiCKRAGETV/SickRage/tarball/master'
2015-09-09 15:39:34 INFO     CHECKVERSION :: Creating update folder F:\Mediaserver\SickRage\sr-update before extracting
2015-09-09 15:39:33 INFO     CHECKVERSION :: Config backup successful, updating...
2015-09-09 15:38:54 INFO     CHECKVERSION :: Config backup in progress...
2015-09-09 15:38:54 INFO     CHECKVERSION :: New update found for SickRage, starting auto-updater ...
```

**Comment by neoatomic** [comment]
You could have found the solution here. :) 
https://github.com/SiCKRAGETV/sickrage-issues

```
IF YOU HAVE ANY UPDATE ERRORS:

Go to SickRage Settings > General > Advanced > Github and enable this setting:

    Git reset (removes untracked files and performs a hard reset on git branch automatically to help resolve update issues)
```

OR

Stop SickRage, SSH(Linux)/CMD(Windows) and enter SickRage folder
```
git remote add upstream https://github.com/SiCKRAGETV/SickRage.git
git fetch upstream
git checkout master
git branch -u upstream/master
git reset --hard upstream/master
git pull
```

**Comment by loungebob** [comment]
I've tried both before posting. Git reset is actually already ticked by default. Even if I untick it, it stays ticked and I see those "Update successful" notices flashing by by the hundreds. They dont stop.

If I try powershell, I get 

F:\mediaserver\sickrage> git remote add upstream https://github.com/SiCKRAGETV/SickRage.git
fatal: Not a git repository (or any of the parent directories): .git

I'm useless :-(

**Comment by neoatomic** [comment]
Well, than i think you can best backup the config.ini and sickbeard.db file and do a clean install. Something definitely got bad with your installation...
Might be a good time to try our brand new windows installer for SickRage. :)

https://github.com/SiCKRAGETV/sickrage-issues/wiki/SickRage-Windows-Installer

**Comment by danielmason30** [comment]
I also have the same issue.

**Comment by loungebob** [comment]
@neoatomic I deleted the SR directory (after backing up the config.ini and the db file), deleted the manually created windows service and used the new Windows Installer to install SR. all went well, but when I start it in IE, I still get the whole notifications bombardement (update successful, config.ini backuped....blabla). See screenshot. And this is before I even copy the old config.ini and db file back - hence on a clean installation. Aint that weird? Btw, it's only in IE, FF and Chrome seem fine and dont show those notification windows....

![snag-0000](https://cloud.githubusercontent.com/assets/8558865/9769680/de0b5a5c-572b-11e5-83b2-e01dde58f4bf.png)

![snag-0001](https://cloud.githubusercontent.com/assets/8558865/9769683/e5e095e4-572b-11e5-8906-d81826e11da3.png)

**Comment by loungebob** [comment]
oh, and the images are broken too. no header images or show images....

**Comment by neoatomic** [comment]
@loungebob Not sure what is happening there...

@OmgImAlexis might be due to jquery.?

**Comment by miigotu** [comment]
@loungebob what version of IE?

**Comment by jacobwvandijk** [comment]
I'm using edge and the images are broken as well.
![image](https://cloud.githubusercontent.com/assets/9477149/9772955/adad14cc-573f-11e5-847a-4d2410ac334e.png)

**Comment by neoatomic** [comment]
Can you mass update the shows with Mass Update.? Should fix the posters/banners.

**Comment by jacobwvandijk** [comment]
Not sure if I did this ok. I checked all checkboxes of the edit and update columns and pressed submit. Reloaded the main page, no luck.

**Comment by miigotu** [comment]
just check update, submit. wait for the update queue to finish.

**Comment by neoatomic** [comment]
@jacobwvandijk Just tested myself on a fresh Windows install and indeed posters/banners are not working. And the notifications keep looping. However when i refresh the page they are gone.

This seems to only effect SickRage installations on Windows. Other operating systems like Linux are working fine.

**Comment by TheMotto9** [comment]
@miigotu I did what you are requesting on Windows based machine, which I'm still running at the moment, and the mass update does not work. 

I've also tried deleting the cache, then performing the mass update .... it shows that the images are being copied to the cache folder from the mass update but all of the posters and banners are still missing after the update completed.

**Comment by TheMotto9** [comment]
I will be switching to Ubuntu tonight but until then, I can be a Windows 10 tester if need be...

**Comment by loungebob** [comment]
@all Windows 10 Build 10532 x64 with IE 11 or Edge. Both not showing images and looping notifications as mentioned above. But as I can see, it's under investigation.

**Comment by OmgImAlexis** [comment]
I'll do an install of Windows 10 later today and see if I can get to the bottom of this, I suspect it's a jQuery issue like you guys said.

**Comment by ripper1967** [comment]
omgimalexis its also windows 7 doing it,i will give you access to mine if you want to check it out...

**Comment by OmgImAlexis** [comment]
@ripper1967 if you could send the details to my email that'd be great. You'll find it on my [profile](https://github.com/OmgImAlexis).

**Comment by captaindoe** [comment]
I can confirm this issue. Running on a Synology NAS, and my error log contains:

2015-09-10 08:40:39 EVENT-QUEUE :: DB error: near "WHERE": syntax error
2015-09-10 08:40:39 EVENT-QUEUE :: Exception generated in thread EVENT-QUEUE: near "WHERE": syntax error

**Comment by WebSpider** [comment]
Which branch/commit are you on @captaindoe ?

**Comment by loungebob** [comment]
any news?

**Comment by neoatomic** [comment]
@loungebob Check this issue for progres.https://github.com/SiCKRAGETV/sickrage-issues/issues/2708

**Comment by captaindoe** [comment]
@WebSpider: I'm on commit BRANCH: (master) / COMMIT: (bb16d3a3e4d3462a73b944c6e7d9384798774ffd). Running python 2.7.10.

**Comment by miigotu** [comment]
@captaindoe you need to do a git pull. Not sure how you got that commit...

**Comment by captaindoe** [comment]
@miigotu when attempting to git pull it says I'm already up-to-date.

DiskStation> /volume1/@appstore/git/bin/git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

**Comment by miigotu** [comment]
I have no clue right now then.

**Comment by captaindoe** [comment]
It's the latest commit (https://github.com/SiCKRAGETV/SickRage/commit/bb16d3a3e4d3462a73b944c6e7d9384798774ffd). Perhaps I should switch to only fetch releases and not the latest commits.

**Comment by loungebob** [comment]
oh my, I see there seems to be a fix. But I have no idea how to install that... :-(

**Comment by WebSpider** [comment]
With the current TVRage issues, this is now 26 commits ago. Please update using the UI, if that does not work, update manually:

```
git remote add upstream https://github.com/SiCKRAGETV/SickRage.git
git fetch upstream
git checkout master
git branch -u upstream/master
git reset --hard upstream/master
git pull
```

**Comment by captaindoe** [comment]
@WebSpider Updating to the current master did the trick. Problem solved for me, great job guys :)

**Comment by MikeyMan83** [comment]
@captaindoe how did you manage that on the synology? I get no response from the GUI when updating

**Comment by miigotu** [comment]
On syno just back up (to a folder outside the package) remove and reinstall the SR package, and restore.

**Comment by captaindoe** [comment]
@MikeyMan83 I updated manually through the terminal. Cd to the directory where SR is downloaded and then run a git pull with the entire file path for the git binary. For me the file path for git was: "/volume1/@appstore/git/bin/git"

**Comment by MikeyMan83** [comment]
Does not seem to be working:
[code]
NAS> /volume1/@appstore/git/bin/git remote add upstream https://github.com/SiCKRAGETV/SickRage.git
fatal: remote upstream already exists.
NAS> /volume1/@appstore/git/bin/git fetch upstream
NAS> /volume1/@appstore/git/bin/git checkout master
Already on 'master'
Your branch is up-to-date with 'upstream/master'.
NAS> /volume1/@appstore/git/bin/git reset --hard upstream/master
HEAD is now at 5391476 Merge branch 'cleaner-regex-tvchaosuk'
NAS> /volume1/@appstore/git/bin/git pull
Already up-to-date.
[/code]

However i still get the message that there are 22 commits.

**Comment by miigotu** [comment]
```
git fetch upstream
git pull
```

**Comment by MikeyMan83** [comment]
Still got issues with the update feature.

I can update manually, but i keep getting the db error:

2015-09-30 10:26:16 ERROR    EVENT-QUEUE :: Exception generated in thread EVENT-QUEUE: near "WHERE": syntax error
AAOperationalError: near "WHERE": syntax error
AA    return self.connection.cursor().execute(query, args)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/db.py", line 80, in _execute
AA    return self._execute(query, args)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/db.py", line 100, in execute
AA    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/db.py", line 201, in action
AATraceback (most recent call last):
2015-09-30 10:26:16 ERROR    EVENT-QUEUE :: DB error: near "WHERE": syntax error
2015-09-30 10:26:16 INFO     EVENT-QUEUE :: Saving all shows to the database
2015-09-30 10:26:15 INFO     EVENT-QUEUE :: Waiting for the SUBTITLESFINDER thread to exit
2015-09-30 10:26:14 INFO     EVENT-QUEUE :: Waiting for the PROPERFINDER thread to exit
2015-09-30 10:26:13 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2015-09-30 10:26:12 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSER thread to exit
2015-09-30 10:26:11 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE thread to exit
2015-09-30 10:26:10 INFO     Thread-55 :: Config backup successful, updating...
2015-09-30 10:26:10 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE thread to exit
2015-09-30 10:26:10 INFO     EVENT-QUEUE :: Waiting for the VERSIONCHECKER thread to exit
2015-09-30 10:26:09 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2015-09-30 10:26:08 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2015-09-30 10:26:07 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCH thread to exit
2015-09-30 10:26:07 INFO     EVENT-QUEUE :: Waiting for the EVENTS thread to exit
2015-09-30 10:26:07 INFO     EVENT-QUEUE :: Aborting all threads
2015-09-30 10:26:07 INFO     CHECKVERSION :: Update was successful!
2015-09-30 10:26:01 INFO     CHECKVERSION :: Config backup successful, updating...
2015-09-30 10:25:12 INFO     Thread-55 :: Config backup in progress...
2015-09-30 10:24:54 INFO     MAIN :: Building internal name cache for all shows
2015-09-30 10:24:54 INFO     CHECKVERSION :: Config backup in progress...
2015-09-30 10:24:54 INFO     CHECKVERSION :: New update found for SickRage, starting auto-updater ...
2015-09-30 10:24:52 INFO     MAIN :: Checking for scene exception updates for AniDB
2015-09-30 10:24:51 INFO     POSTPROCESSER :: Processing completed
2015-09-30 10:24:50 INFO     MAIN :: Checking for XEM scene exception updates for theTVDB
2015-09-30 10:24:50 INFO     POSTPROCESSER :: PostProcessing Path: /volume1/downloads/dst/Series
2015-09-30 10:24:50 INFO     MAIN :: Checking for scene exception updates for theTVDB
2015-09-30 10:24:50 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8899/
2015-09-30 10:24:49 INFO     MAIN :: 280820: Unable to find IMDb show info in the database
2015-09-30 10:24:49 INFO     MAIN :: 250342: Unable to find IMDb show info in the database
2015-09-30 10:24:48 INFO     MAIN :: Writing PID: 4944 to /usr/local/sickrage/var/sickrage.pid
2015-09-30 10:24:48 INFO     MAIN :: Checking for shows with tvrage id's, since tvrage is gone
2015-09-30 10:24:00 INFO     MAIN :: Signal 15 caught, saving and exiting...

And that is even after i did a full reinstall several times.

**Comment by miigotu** [comment]
@MikeyMan83 that error has nothing to do with the updater. You need to manually git pull ONCE to get past the bad commit, or install A NEW DOWNLOAD of master.

**Comment by MikeyMan83** [comment]
I will do that now, but i must say i've been having this issue for the last weeks or so. 
Did a fresh install last week.

**Comment by miigotu** [comment]
Being as this issue was resolved just over a week ago...

**Comment by MikeyMan83** [comment]
Just updated, hope for the last time manually :)

**Comment by MikeyMan83** [comment]
Just got 14 new commits, pressed the update now button, same result:

2015-10-02 08:55:08 ERROR    EVENT-QUEUE :: Exception generated in thread EVENT-QUEUE: near "WHERE": syntax error
AAOperationalError: near "WHERE": syntax error
AA    return self.connection.cursor().execute(query, args)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/db.py", line 80, in _execute
AA    return self._execute(query, args)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/db.py", line 100, in execute
AA    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/db.py", line 201, in action
AATraceback (most recent call last):
2015-10-02 08:55:08 ERROR    EVENT-QUEUE :: DB error: near "WHERE": syntax error
2015-10-02 08:55:05 INFO     EVENT-QUEUE :: Saving all shows to the database
2015-10-02 08:55:05 INFO     EVENT-QUEUE :: Waiting for the SUBTITLESFINDER thread to exit
2015-10-02 08:55:04 INFO     EVENT-QUEUE :: Waiting for the PROPERFINDER thread to exit
2015-10-02 08:55:03 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2015-10-02 08:55:03 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSER thread to exit
2015-10-02 08:55:02 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE thread to exit
2015-10-02 08:55:01 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE thread to exit
2015-10-02 08:55:01 INFO     EVENT-QUEUE :: Waiting for the VERSIONCHECKER thread to exit
2015-10-02 08:55:00 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2015-10-02 08:54:59 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2015-10-02 08:54:59 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCH thread to exit
2015-10-02 08:54:59 INFO     EVENT-QUEUE :: Waiting for the EVENTS thread to exit
2015-10-02 08:54:59 INFO     EVENT-QUEUE :: Aborting all threads
2015-10-02 08:54:50 INFO     Thread-62 :: Config backup successful, updating...
2015-10-02 08:54:44 INFO     Thread-20 :: Processing completed

**Comment by WebSpider** [comment]
I see no debug messages about the update actually happening.

Can you attach debug log?

-----Original Message-----

**Comment by MikeyMan83** [comment]
Here you go:

https://gist.github.com/MikeyMan83/6ac39861edcafab8d58e#file-gistfile1-txt

**Comment by WebSpider** [comment]
Well, the hint I am getting from this, is that for some reason, SR doesn't restart.

Can you shut down SR, then perform a git reset: https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ's-and-Fixes#update-problems-try-this

**Comment by MikeyMan83** [comment]
If you read above, you can see that i've been doing that a couple of times already.
The manual Git update works fine. However, it should work from the GUI.

I see that SR is having problems restarting. The update process shows a successful stop, then the start seems to fail. However; after that i can access SR without problems.
But the update still fails.

**Comment by WebSpider** [comment]
Actually, it's the shutdown that fails, when it is trying to commit the changes it has cached, but not yet saved to database.

Without looking into your database in detail, i'd say your best way forward is to stop SR, save your config.ini, remove the cache/, sickbeard.db, cache.db and failed.db (or copy them to another location), restart SR and re-add the shows by using Shows > Add Shows > Add Existing Shows

Depending on the amount of shows/eps you have, this may take a while.

**Comment by MikeyMan83** [comment]
Hi Guys,

I rebuilt my whole dbase, and the latest commits seem to update fine now.

Thanks!
