### ISSUE TITLE
Still unable to switch to develop

### ISSUE THREAD

**Issue by kendog819** [SiCKRAGETV/sickrage-issues#2880]
![image](https://cloud.githubusercontent.com/assets/11353628/9982829/c4bc67f6-5fb6-11e5-9733-82ddfe904c93.png)

![image](https://cloud.githubusercontent.com/assets/11353628/9982838/17e308e0-5fb7-11e5-8c2a-e883cb9f6976.png)

Was told to wait for the master yesterday by @neoatomic .. Master is out, still having problem.

https://github.com/SiCKRAGETV/sickrage-issues/issues/2866

Any help appreciated,
Ken

**Comment by fernandog** [comment]
@kendog819 please stop SR, replace your SickRage/sickbeard/versionChecker.py file with this 
https://raw.githubusercontent.com/SiCKRAGETV/SickRage/f02524977879ed2fabd56730e1b7b65d7114be13/sickbeard/versionChecker.py

start SR and report back

**Comment by kendog819** [comment]
Not sure if I did this right, but I went to that page and saved the file, it saved it as "versionChecker.py.txt" 

I moved it to the proper location, renamed it, removing .txt off the end, and am getting this error now.

![image](https://cloud.githubusercontent.com/assets/11353628/9983269/b27731bc-5fc4-11e5-834c-f19ace25b535.png)

**Comment by fernandog** [comment]
@kendog819 that is it. thanks! how did you install SickRage? 'git clone .....' ? 

@miigotu

**Comment by kendog819** [comment]
No..it's QSickrage

**Comment by kendog819** [comment]
I'm also still receiving the error on my pc that used the windows installer as well. Should I add the versionChecker.py to that machine also, or is that not helping?

Thanks

**Comment by fernandog** [comment]
Please post the contents of localhost:8081/config

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/9983410/865ce0dc-5fc8-11e5-9ae1-a42b3671cd30.png)

**Comment by fernandog** [comment]
Dont know what is happening then. Will wait @miigotu

**Comment by kendog819** [comment]
I'm also still receiving the error on my pc that used the windows installer as well. Should I add the versionChecker.py to that machine also, or is that not helping?

**Comment by fernandog** [comment]
Dont need

**Comment by kendog819** [comment]
ok

**Comment by miigotu** [comment]
@kendog819 your github username is not your email, it is kendog819

**Comment by kendog819** [comment]
I've tried it both ways, because when logging into the site it asks you for one or the other.

![image](https://cloud.githubusercontent.com/assets/11353628/9991916/5cf6f448-603c-11e5-9a5a-54fcb86a09c5.png)

**Comment by miigotu** [comment]
@kendog819 well, currently develop and master are the same right now, because I just released v4.0.65

We will work on fixing this for the next release as long as I can reproduce it (if it isnt already fixed).

**Comment by kendog819** [comment]
Is there some other issue going on right now? I can't connect to sickrage from either of my systems.

**Comment by miigotu** [comment]
Might need a manual git pull, stupid bug I missed: SiCKRAGETV/sickrage-issues/issues/2883

**Comment by kendog819** [comment]
No Idea how to do that, on m qnap using qsickrage. Do I need to putty into something?

**Comment by kendog819** [comment]
Not being able to switch to develop is now working on my windows machine. So I suppose we can close this, still having issues on my qnap nas though, which a different thread was opened for.
