### ISSUE TITLE
Boxcar2 not functioning

### ISSUE THREAD

**Issue by spirro** [SiCKRAGETV/sickrage-issues#311]
I've just installed SickRage and have noticed an issue with notifications using Boxcar2. The test is failing with the error below in the logs:

2014-12-31 16:35:39 Thread-21 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 230, in async_call
    result = function(**kwargs)
TypeError: testBoxcar2() got an unexpected keyword argument 'accessToken'

**Comment by timrettop** [comment]
I'm also experiencing this issue.  

Enabled debug logs and get the following: 

```
2015-01-02 15:58:51 ERROR    Thread-16 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/tim/.sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
TypeError: testBoxcar2() got an unexpected keyword argument 'accessToken'
Traceback (most recent call last):
  File "/home/tim/.sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
TypeError: testBoxcar2() got an unexpected keyword argument 'accessToken'
2015-01-02 15:58:51 ERROR    Uncaught exception GET /home/testBoxcar2?accessToken=******************* (10.1.50.178)
HTTPServerRequest(protocol='http', host='10.1.50.16:8081', method='GET', uri='/home/testBoxcar2?accessToken=*******************', version='HTTP/1.1', remote_ip='10.1.50.178', headers={'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'Host': '10.1.50.16:8081', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://10.1.50.16:8081/config/notifications/', 'Cookie': '_ga=GA1.1.2024531446.1419465788; advanced_toggle_checked=1; late_view2=list; manage_view2=details; plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; SESSION-GUID=ogbhcuu1mzh; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=suggestions; user="2|1:0|10:1420236939|4:user|44:ZTJjNTgyZDI0NGZhMjkwZTQzMWM1MjFjZTQ4ZDJkOGI=|d4154a27745bb85a1a3239b7561bed88bdbdeff037c53d0b5322b7a8e987a698"; wanted_view2=details'})
Traceback (most recent call last):
  File "/home/tim/.sickrage/tornado/web.py", line 1292, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/home/tim/.sickrage/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/home/tim/.sickrage/tornado/concurrent.py", line 226, in <lambda>
    lambda future: callback(future.result()))
  File "/home/tim/.sickrage/lib/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/home/tim/.sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/home/tim/.sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/home/tim/.sickrage/lib/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tim/.sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
TypeError: testBoxcar2() got an unexpected keyword argument 'accessToken'
```

**Comment by fernandog** [comment]
python? OS? branch? hash?

**Comment by spirro** [comment]
Python 2.7.3 Windows 7 64 bit. Master branch. Hash 33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8

**Comment by timrettop** [comment]
Python 2.7.6 Ubuntu 14.04 x64.  Master branch. Hash 33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8

**Comment by tchirou** [comment]
Win 8.1
Python 2.7.6
Branch develop 8b84e4f4bc6cdebdc605438e9e75d15f1133d65e
No problem with boxcar2

Have you checked if there is a space at the end of your token ?
Has it ever worked before ?

**Comment by spirro** [comment]
I've never used SickRage before. I just started using it a few days ago.

Strange thing is Boxcar2 seems to work as expected when snatching a show. It just seems to fail when you press the 'Test' button.

**Comment by tchirou** [comment]
Does it work when a download is finished ?

**Comment by spirro** [comment]
Yes. For me it's only the Test that fails

**Comment by tchirou** [comment]
Actually, I have the same when I try a test on the develop branch.
This is a very low priority bug as it works as intended on snacth and download (I say this for the guys labeling the issues).

**Comment by fernandog** [comment]
stop SR, edit you SickRage/sickbeard/notifiers/boxcar2.py:

from:
```
    def test_notify(self, accesstoken, title="SickRage : Test"):
        return self._sendBoxcar2("This is a test notification from SickRage", title, accesstoken)
```
to
```
    def test_notify(self, accesstoken=None, title="SickRage : Test"):
        return self._sendBoxcar2("This is a test notification from SickRage", title, accesstoken)
```

restart SR and test please.

**Comment by spirro** [comment]
This doesn't seem to have worked for me

**Comment by fernandog** [comment]
@spirro I edited the code after I posted. did you see? Don't use the code from email but from git page.

**Comment by spirro** [comment]
I've used the code from the GIT page but still failing. Here is the code just in case something is missing:

class Boxcar2Notifier:
    def test_notify(self, title="SickRage : Test"):
        return self._notifyBoxcar2("This is a test notification from SickRage", title)

**Comment by spirro** [comment]
I'm no developer but doesn't this need updating in webserve.py:

def testBoxcar2(self, accesstoken=None):
        # self.set_header('Cache-Control', 'max-age=0,no-cache,no-store')

**Comment by fernandog** [comment]
@spirro its strange cause the SNATCH code is similar:

    def notify_snatch(self, ep_name, title=notifyStrings[NOTIFY_SNATCH]):
        if sickbeard.BOXCAR2_NOTIFY_ONSNATCH:
            self._notifyBoxcar2(title, ep_name)

**Comment by fernandog** [comment]
@abeloin can you check this one. seems easy but I couldn't fix.

**Comment by abeloin** [comment]
@fernandog See this [commit](https://github.com/abeloin/SickRage/commit/cb68f649ea1d725249d13ca27daafe05f4e8a7e8) I think it should solve the issue but I don't have an iPhone so I can't test it.

@spirro Can you try this [commit](https://github.com/abeloin/SickRage/commit/cb68f649ea1d725249d13ca27daafe05f4e8a7e8)?

**Comment by abeloin** [comment]
@timrettop Can you try this [commit](https://github.com/abeloin/SickRage/commit/cb68f649ea1d725249d13ca27daafe05f4e8a7e8)?

**Comment by timrettop** [comment]
@abeloin I'm having some trouble getting sick rage to access the configuration menus since backing up the config and database, blowing away the directory, and cloning develop and restoring the settings. 

I'm running into issue #407 but stopping the service and starting it again doesn't resolve the issue. 
Besides the LOG_NR error when accessing the General menu, I also get this error when accessing the Notifications menu: 

```
2015-01-31 09:20:02 Thread-40 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/tim/.sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/home/tim/.sickrage/sickbeard/webserve.py", line 4322, in index
    try:
  File "/home/tim/.sickrage/cache/cheetah/cheetah__home_tim__sickrage_gui_slick_interfaces_default_config_notifications_tmpl_1422724802_73_87114.py", line 2006, in respond
    if VFFSL(SL,"sickbeard.USE_FREEMOBILE",True) : # generated from line 1220, col 118
NotFound: cannot find 'USE_FREEMOBILE' while searching for 'sickbeard.USE_FREEMOBILE'
```

**Comment by timrettop** [comment]
@abeloin Nevermind, found the issue, stuck process.   

I'm getting an error when testing the 'Test Boxcar2' option: 


```
2015-01-31 09:37:34 ERROR    Thread-21 :: Failed doing webui callback: Traceback (most recent call last):
AATypeError: testBoxcar2() got an unexpected keyword argument 'accessToken'
AA    result = function(**kwargs)
AA  File "/home/tim/.sickrage/sickbeard/webserve.py", line 230, in async_call
AA    result = self.fn(*self.args, **self.kwargs)
AA  File "/home/tim/.sickrage/lib/concurrent/futures/thread.py", line 61, in run
AA    exec('raise exc_type, exc_value, traceback', {}, locals_)
AA  File "/home/tim/.sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise
AA    reraise(self._exception, self._traceback)
AA  File "/home/tim/.sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result
AA    return self.__get_result()
AA  File "/home/tim/.sickrage/lib/concurrent/futures/_base.py", line 400, in result
AA    lambda future: callback(future.result()))
AA  File "/home/tim/.sickrage/tornado/concurrent.py", line 226, in 
AA    ret = fn(*args, **kwargs)
AA  File "/home/tim/.sickrage/tornado/stack_context.py", line 314, in wrapped
AA    raise_exc_info((type, value, traceback))
AA  File "/home/tim/.sickrage/tornado/web.py", line 1292, in _stack_context_handle_exception
AATraceback (most recent call last):
AAHTTPServerRequest(protocol='http', host='10.1.50.16:8081', method='GET', uri='/home/testBoxcar2?accessToken=*******************', version='HTTP/1.1', remote_ip='10.1.50.177', headers={'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'Host': '10.1.50.16:8081', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://10.1.50.16:8081/config/notifications/', 'Cookie': '_ga=GA1.1.2024531446.1419465788; advanced_toggle_checked=1; late_view2=list; manage_view2=details; plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; SESSION-GUID=zoetwxsm7ka; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=suggestions; user="2|1:0|10:1422420849|4:user|44:ZTJjNTgyZDI0NGZhMjkwZTQzMWM1MjFjZTQ4ZDJkOGI=|69d93c7040c8d853d229740d46a8e8c17f8df84f157d643f2f1aac08648c29ee"; wanted_view2=details'})
AA2015-01-31 09:36:24 ERROR    Uncaught exception GET /home/testBoxcar2?accessToken=******************* (10.1.50.177)
AATypeError: testBoxcar2() got an unexpected keyword argument 'accessToken'
AA    result = function(**kwargs)
AA  File "/home/tim/.sickrage/sickbeard/webserve.py", line 230, in async_call
AATraceback (most recent call last):
AATypeError: testBoxcar2() got an unexpected keyword argument 'accessToken'
AA    result = function(**kwargs)
AA  File "/home/tim/.sickrage/sickbeard/webserve.py", line 230, in async_call
```

**Comment by abeloin** [comment]
@timrettop Can you confirm you applied the commit in my previous comment?

**Comment by timrettop** [comment]
@abeloin Oh geez, I should read shouldn't I.  After applying that commit, it worked perfectly!   Thanks!

**Comment by abeloin** [comment]
@timrettop Thank you for testing this commit.

@fernandog Fixed with pull request SiCKRAGETV/SickRage#1268

**Comment by fernandog** [comment]
thanks again!

**Comment by fernandog** [comment]
@spirro develop updated. please test and report back

**Comment by tchirou** [comment]
It is working for me.
