### ISSUE TITLE
SickRage won't start on my synology

### ISSUE THREAD

**Issue by beschoenen** [SiCKRAGETV/sickrage-issues#682]
i have no idea why, but my sickrage won't start. I Reverted back to the master branch by hand using git on my synology but that didn't change anything.

Log: http://pastebin.com/hgNRiKAz

**Comment by fernandog** [comment]
@neoatomic help here with nas?

**Comment by neoatomic** [comment]
@beschoenen 
Could be the same problem as this. https://github.com/SiCKRAGETV/sickrage-issues/issues/665#issuecomment-75041585

Look in your Sickrage folder if there is a folder named "restore"
/volume1/@appstore/sickbeard-custom/var/SickBeard/restore
Remove that folder and try to restart Sickrage in the package center. That should fix it.

**Comment by beschoenen** [comment]
There's no 'restore' folder there, there was one at /volume1/@appstore/sickbeard-custom/var, I deleted it but SickRage still doesn't boot, even after a reboot of my nas.

**Comment by neoatomic** [comment]
You are right the folder is under "var". Does the log show any errors when you start SR.? 
Take a look if there is another folder named something like "cache-20150220xxx" and remove it.
If that still doesn't work than please reinstall sickbeard-custom/sickrage so you have a fresh install.

I had simulair problems yesterday where the restore function was preventing SR from booting. I only needed to remove the restore folder to get SR to start again.

**Comment by beschoenen** [comment]
So, I manually checked out the develop branch again, at now it started again, so removing the restore folder probably fixed it.

**Comment by neoatomic** [comment]
Glad it worked. Please close this issue so the developers can move on to other problems.

**Comment by beschoenen** [comment]
Though switching to the master branch kills it again

**Comment by neoatomic** [comment]
Did you check again for the restore folder on master.?

@fernandog any ideas.?

**Comment by beschoenen** [comment]
As far as i know there's no difference in folders with git

**Comment by fernandog** [comment]
@beschoenen enter Sickrage folder, and run "python SickBeard.py". see what happens and post any error

**Comment by beschoenen** [comment]
It says i need cheetah

**Comment by fernandog** [comment]
other than that

**Comment by abeloin** [comment]
@fernandog We pushed some fixes to the backup/restores process to develop but those aren't in master yet.

**Comment by fernandog** [comment]
@abeloin cheetah is missing in his setup

**Comment by beschoenen** [comment]
It's running atm though, on the develop branch

**Comment by beschoenen** [comment]
So, I have to wait for the commits to be pushed to the master branch?

**Comment by abeloin** [comment]
Yes stay on develop for the moment I'll update this issue the merge is done

**Comment by abeloin** [comment]
@fernandog Yes it's missing globally but not locally that is why it start via the interface but not via ssh.
