### ISSUE TITLE
Issue with post-processing

### ISSUE THREAD

**Issue by GMBrian** [SiCKRAGETV/sickrage-issues#695]
I'm running SickRage on my synology DS214play.

My issue is that SickRage is not post-processing. Even manually it gives the following error:

Processing folder /volume1/video/series/~New
TV_DOWNLOAD_DIR: /volume1/video/series/~New
Found temporary sync files, skipping post processing

Also, in the log I find the following warnings:

2015-02-21 02:38:12 WARNING  Thread-57 :: Found temporary sync files, skipping post processing
2015-02-21 02:36:38 WARNING  POSTPROCESSER :: Found temporary sync files, skipping post processing

Can someone tell me how to remove those sync files manually? I can't seem to find any hidden files in the downloads folder.

**Comment by vladsjc** [comment]
I have exactly the same problem. It started last week, it must be the last Update. My download dir stopped from post processing, and when i did the manual post process it gave me the same error:

Thread-58 :: Found temporary sync files, skipping post processing

My download dir is a CIFS mount (maybe that information will help), from my NAS.  I had to create subdirs and move the downloaded files to there, and finally the manual post-processing task worked, then I remove the main download DIR. However that issue is happening again, so it may be some code problem.

**Comment by fernandog** [comment]
if you have any of this file in the folder SR don't process it:
extension == '!sync' or extension == 'lftp-pget-status' or extension == 'part' or extension == 'bts'

this happens when file is seeding, or still downloading, or using Bitorrent sync, etc

**Comment by vladsjc** [comment]
But this is happening after i finished downloaded some of the files, and I am sure there weren't any file like this. This is the folder content:

drwxr-xr-x 0 www-data www-data         0 Feb 19 17:57 Bates.Motel.S01E06.SWESUB.HDTV.XviD.MP3-little_devil
drwxr-xr-x 0 www-data www-data         0 Feb 20 02:56 Elementary.S03E15.HDTV.x264-LOL[ettv]
-rwxr-xr-x 1 www-data www-data 129273698 Feb 20 00:35 The.Big.Bang.Theory.S08E15.HDTV.x264-LOL.mp4

 the download process have finished for Elementary.S03E15.HDTV.x264-LOL[ettv] and for the file The.Big.Bang.Theory.S08E15.HDTV.x264-LOL.mp4. But inside the folder Bates.Motel.S01E06.SWESUB.HDTV.XviD.MP3-little_devil, the download process didn't finished. But the post-processing task didn't process any of this files.

**Comment by fernandog** [comment]
@vladsjc @GMBrian can you try to enable "Postpone post processing" setting?

@djoole is that it?

**Comment by djoole** [comment]
Actually they have to disable it.
@adam111316 asked to me to make it enabled by default (safer option) : https://github.com/SiCKRAGETV/SickRage/pull/783
So people having !sync files in their folder and wanting post processing not to wait for the sync to be finished, should disable the option.

**Comment by fernandog** [comment]
but what about a folder with more than one episode and just one !sync file? will it don't PP all the other files?

**Comment by djoole** [comment]
No, that was the original "issue" mentioned here : https://github.com/SiCKRAGETV/SickRage/pull/782#issuecomment-54734603

Hence my mod to disabling postponing and the option to enable/disable (enabled by default)

**Comment by fernandog** [comment]
what about this kind of issues? we have some of them: https://github.com/SiCKRAGETV/sickrage-issues/issues/690

**Comment by fernandog** [comment]
@djoole but syncing files in linux are locked so sickrage won't be able to process, isn't? what about other OS without the locked files?

**Comment by fernandog** [comment]
another one just pop out: https://github.com/SiCKRAGETV/sickrage-issues/issues/696

**Comment by djoole** [comment]
Not sure they are locked.. But the sure thing is (at least on my freebsd system) SR don't try to PP them and wait nicely for them to be synced.

I don't know why issues are hoping out now, because this option has been merged 5 months ago...

**Comment by djoole** [comment]
I'm 203 commits behind... maybe something has been changed in this huge update? Something breaking the postponing function?

**Comment by fernandog** [comment]
we just fixed the auto-submit issue =)

**Comment by djoole** [comment]
what is this auto-submit issue?

**Comment by fernandog** [comment]
when an error appears in the LOG for the user, he has the option to hit a button to auto open an issue here in GITHUB. All this issues has "[APP SUBMITTED]" in the title

**Comment by djoole** [comment]
ok..

Well all I can tell is the changes i've made in september about disabling PP postponing when sync files are still present (because there are always sync files in my dl dir!) is only active if people do uncheck the option in PP settings.

@Kallb123 let it check, so must be something else..

**Comment by vladsjc** [comment]
@fernandog I dont know the algorithms behind the post-processing, but for me it is strange that if I have a folder, for example: /mnt/download, and inside this folder I have 3 subfolders, for 3 different series/episodes, Ex:

/mnt/download/serieA/episode1.xxx
/mnt/download/serieB/episode1.xxx
/mnt/download/serieC/episode1.xxx

What it is happening, at least for me, If i have chosen the /mnt/download as my download DIR, and i have finished downloading the files in serieA and SerieB, but not yet on SerieC, it stopped all post-process at all. Why not treat every sub-folder as a sub process?? (maybe i am wrong, and it is treated as a sub process)

**Comment by fernandog** [comment]
@vladsjc you **MUST** have a incomplete folder and a complete folder BUT you can disabled postpone setting. all downloader have this incomplete and complete folder setting

**Comment by adam111316** [comment]
@djoole: I left sickrage, so I can't comment sorry.

**Comment by djoole** [comment]
no problem..

@fernandog i found the commit i made : https://github.com/SiCKRAGETV/SickRage/commit/6a393cc7555da05514b9d10e1eaab96cbd67a3e3
It was in sept 7 2014..
Must have nothing to do with these new issues reported, @vladsjc reported that he has the problem since only one week

**Comment by fernandog** [comment]
@djoole not blaming you. just wanted to know about the postpone. sorry

**Comment by djoole** [comment]
no problem :)

**Comment by vladsjc** [comment]
@fernandog I have 2 different folders. One for downloading files (TV Download Dir) and another one to copy since the download are complete (My Series folder). I was talking about just the download folder (some torrents have the file inside a folder),

**Comment by Kallb123** [comment]
@vladsjc I think what @fernandog was referring to was a folder for incomplete downloads, for files still being transferred by Transmission or whatever. So they are in transit in "Downloading"  folder, then get put into a "Downloaded" folder, then SR PPs them into your actual series folders.

**Comment by fernandog** [comment]
You need 3:
Incomplete (still downloading)
Complete (finished downloading and waiting PP)
Series folder (main folder were all series are. One subfolder for each tvshow

**Comment by GMBrian** [comment]
Disabling the Post-pone post processing options worked to get rid of the message. I wonder why I didn't manage to read that option. I also guess it's not the real solution to what's going on but it'll work fine for now. Thanks!

**Comment by fernandog** [comment]
Couchpotato saves to this folder too? Maybe its creating the sync files

**Comment by vladsjc** [comment]
@fernandog Thanks for your help, and for this great product. I always worked with 2 folders, and all things were OK, but I will change the config in transmition, that is not a problem.

**Comment by fernandog** [comment]
@vladsjc we still didn't found the root cause. I need to make this tests

**Comment by vladsjc** [comment]
If this can help, i use a exclusive download dir for sickrage, no couchpotato or other thing in the same dir. If you need i can send more information about my setup.

**Comment by TagForce** [comment]
@fernandog @vladsjc 
The root cause is that SR creates a file list before it runs PP. If that contains any sync file it will halt the entire PP run. It will be changed to just skip the folder it found the syncfiles in.

**Comment by djoole** [comment]
@TagForce When you change this, please let the postpone switch intact, as the new way won't still be enough for me.
I only have files in the download dir, not subdirectories, so a better change would be to postpone PP of only sync files and PP the rest, even if everything (synced files and BT !sync files) is in the root of download dir.

**Comment by TagForce** [comment]
@djoole Postpone switch will be left in tact, it will only do a more sane check for syncfiles (which also will be user configurable in the settings).

**Comment by djoole** [comment]
Great.
But i think the the more perfect thing would be that postpone just impact the synced file, not the entire download dir.

Ex : there is these files in the download dir :

serie1.s01e1.mkv
serie1.s01e2.mkv.!sync
serie1.s01e3.mkv

Wanted (by me :) ) behaviour : 
PP on ep 1 and 3 can be done by SR
PP on ep 2 is postponed until it's synced

Behaviour as it is (with postpone switch activated) :
No PP at all until ep 2 is synced...

**Comment by TagForce** [comment]
@djoole So basically what you're saying is:
Change the syncfile check into a filter, and perform postprocessing on set(videofiles) - set(syncfiles)?
That could work, I'll need to test that.

**Comment by djoole** [comment]
@TagForce exactly. This way, we wouldn't need anymore the option i added to disable postponing.

**Comment by TagForce** [comment]
@djoole This is rapidly becoming more complicated...
Syncfiles are never videofiles (as videofiles have a video extension like .mkv, .avi, etc), so performing a process on set(videofiles) - set(syncfiles) will still result in syncfiles being post processed as part of the set of videofiles.

So your example above will already work (even without postpone switch on) as serie1.s01e02.mkv.!sync is not a videofile.

That being said, it's good to handle syncfiles, and to have it just skip the current episode, but it means we'll have to grab a list of associated_files for the current videofile... I'll get it, but it's a bit more difficult than I thought.

**Comment by fernandog** [comment]
@TagForce listing all associated files we can add (in the future) another feature request that is ONLY PP videos with external subtitles (.srt) - for user who download subtitles using other modules like periscope

**Comment by djoole** [comment]
@TagForce you lost me there.. I understand in what you said the my exemple should already work as it is?
Because it's not, that's why I had to make an option to disable postpone in the first place.
SR stop PostProcessing as soon as there is a sync file in the download dir, no matter if there are also completed video files.

If it was behaving like you say, I would never have added this option..

See comments from this PR : https://github.com/SiCKRAGETV/SickRage/pull/782

**Comment by TagForce** [comment]
@djoole Yeah, I meant that the postpone if syncfile option turned off will work for you or anybody. It simply won't process syncfiles as videofiles, ever. The only issue with syncfiles can occur when it is an associated file. But checking for syncfiles there and then breaking out of the process run for that videofile is not as straightforward as I thought.
